### ISSUE TITLE
Error al cargar módulo

### ISSUE THREAD

**Issue by pabloigrana** [mercadopago/cart-magento#103]
Chicos, actualicé el módulo de MP borrando antes las carpetas y directorios que están detallados y cuando al borrar la caché de Magento me sale el siguiente error:

Parse error: syntax error, unexpected '[' in ...../app/code/community/MercadoPago/MercadoEnvios/Model/Observer.php on line 128

**Comment by fcapua-summa** [comment]
Hola @pabloigrana, ese error seguramente es porqué no estás corriendo con PHP 5.4 o más como se indica en los requerimientos de Magento 1.x: http://devdocs.magento.com/guides/m1x/system-requirements.html

Saludos!

**Comment by pabloigrana** [comment]
Es verdad! Está corriendo bajo la versión 5.3.29, mil gracias!

**Comment by fcapua-summa** [comment]
De nada!
