### ISSUE TITLE
Problema costos de envío

### ISSUE THREAD

**Issue by pabloigrana** [mercadopago/cart-magento#104]
Qué tal chicos, estoy teniendo problemas con el módulo de MercadoPago para Magento. En el checkout selecciono la opción de envío normal y cuando pasa a MercadoPago no arrastra el costo, figura como gratis, cuando yo tengo deshabilitada la opción desde la configuración de MercadoEnvíos en Magento. La única opción que me queda es seleccionar envío prioritario en MercadoPago y si bien se termina pagando por el servicio prioritario, a Magento le llega que se pagó por el normal y genera una deuda en el detalle del pedido. 
Si en lugar de normal elijo la opción prioritario en el checkout, después en MercadoPago me lo transforma automaticamente a gratuito. Es un erro del módulo entiendo no? Alguien con el mismo problema? Adjunto las capturas de pantalla...
![capturas mercadopago](https://cloud.githubusercontent.com/assets/17443346/13375254/7aff1096-dd79-11e5-8e88-46215266ea61.jpg)

**Comment by fcapua-summa** [comment]
Hola @pabloigrana, vamos a revisar lo que mencionas y te informaremos que es que ha ocurrido.

Saludos!

**Comment by pabloigrana** [comment]
Perfecto @fcapua-summa , si necesitan cualquier otro dato me avisan. Saludos!

**Comment by fcapua-summa** [comment]
Hola @pabloigrana, ya está disponible para descargarte una nueva versión del plugin que solucionar el problema que reportaste: https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x

Esperamos tu respuesta para dar por cerrado el issue.

¡Gracias!

**Comment by pabloigrana** [comment]
Qué tal @fcapua-summa , estuve probando el nuevo plugin y se solucionó el problema relacionado con el envío gratis, pero aún no termina de arrastrar bien los costos de envío cuando uno pasa del checkout de Magento hacia MercadoPago, pasa tanto en envío normal como prioritario. Te adjunto captura.

![costos envio](https://cloud.githubusercontent.com/assets/17443346/13448697/d1dbb842-e003-11e5-8cb1-91852efa3343.jpg)

Aprovecho para preguntarte dos cosas. La etiqueta de envío que se genera en Magento es correcta? Consulto ya que la etiqueta de Mercado Envíos cuando uno compra por medio de MercadoLibre difiere de esta y tiene muchos más datos, solo es una duda...

![envio](https://cloud.githubusercontent.com/assets/17443346/13449074/b4dc177a-e006-11e5-87c0-5a6497353db8.jpg)

La otra pregunta es referida a las notificaciones de estados en el pedido. Es correcto que se generen siete notificaciones en un pedido que se abonó con tarjeta? Todos corresponden a la misma venta, fue la que utilicé para corroborar la actualización del plugin. Después de dos "procesando" hay un "completo" y luego otra vez tres "procesando" y en ese estado queda el pedido.

![estados_pago](https://cloud.githubusercontent.com/assets/17443346/13449163/934f6cc8-e007-11e5-9ae8-93d93ece2faa.JPG)

Saludos y desde ya gracias.

**Comment by fcapua-summa** [comment]
Hola @pabloigrana te respondo algunas de tus consultas.

Respecto a que no ves el monto de envío hasta no seleccionarlo en el iframe de MercadoPago, es así como funciona. 
Desde el lado de Magento se genera la cotización y se muestra el total, pero en definitiva la selección tiene que hacerse en MercadoPago. Estamos analizando internamente alternativas para mejorar la experiencia del usuario.

Respecto a la diferencia de las obleas estamos chequeando con los otros equipos involucrados para darte una respuesta a ese punto.

Finalmente, respecto a los repetidas notificaciones, hemos detectado un posible bug de nuestro lado y hemos subido el fix. 
Si te vuelve a suceder es posible que sea porque se generó un error en tu servidor y MercadoPago ante esta situación trata de reenviar la notificación; en este caso te voy a pedir que nos agregues la información del log de PHP.

**Comment by fcapua-summa** [comment]
Hola @pabloigrana , estamos revisando tu consulta respecto a la oblea de envio.

Para poder verificar que ha ocurrido en tu caso necesito el shipment_id, este lo podes obtener de la URL donde se genera la oblea, que tiene un formato similar a este:
 api.mercadolibre.com/shipment_labels?shipment_ids=**:shipment_id**&response_type=zpl2&access_token=:access_token

**Comment by fcapua-summa** [comment]
Además si podes enviarnos los PDFs generados que son distintos, para poder compararlos también nos vendría bien.

Gracias!

**Comment by pabloigrana** [comment]
Qué tal @fcapua-summa , te paso lo que me solicitaste.

**1. URL de la oblea que se genera en Magento:**

https://api.mercadolibre.com/shipment_labels?shipment_ids=21528128041&response_type=zpl2&access_token=APP_USR-7620317504511381-030823-ad42e5269f78d0f7a7ed8eb67b3b6904__N_B__-89753350

**2. PDF generado desde el sitio de MercadoPago:**

[d684d3b6dc4d4095aa45066c5c9f63e6_labels.pdf](https://github.com/mercadopago/cart-magento/files/164371/d684d3b6dc4d4095aa45066c5c9f63e6_labels.pdf)

**3. Respecto a esto hago una aclaración, si quiero imprimir la etiqueta desde el mail que me llega como vendedor, arroja el siguiente error:**

![error_etiqueta](https://cloud.githubusercontent.com/assets/17443346/13624436/e196a31c-e58c-11e5-8c6e-8ebbcebd8183.jpg)

Si entro desde la cuenta de MercadoPago puedo imprimir la etiqueta sin problemas:

![etiquetaok](https://cloud.githubusercontent.com/assets/17443346/13624462/1af7c55a-e58d-11e5-9e3b-adcfb8c0dc19.jpg)

**4. PDF generado desde Magento, te adjunto los dos archivos que vienen dentro de la carpeta comprimida. Uno es .pdf y el otro un .txt, este último es para las impresoras térmicas tengo entendido y viene encriptado, pero se llegan a ver datos que no están en el PDF, tal vez esta etiqueta viene OK como la de MP y el problema es solo con el PDF.**

[Control.pdf](https://github.com/mercadopago/cart-magento/files/164389/Control.pdf)
[Etiqueta de envio.txt](https://github.com/mercadopago/cart-magento/files/164388/Etiqueta.de.envio.txt)

**5. Noté también que desde pedidos, en la solapa de información no funciona el rastreo de envíos, arroja el siguiente error, no así desde la solapa de envíos que ambos te llevan a OCA:**

![error_envio](https://cloud.githubusercontent.com/assets/17443346/13624613/946337fc-e58e-11e5-8b56-54c776e944e3.jpg)

**6. Por último, me sigue generando varios estados de pedido, te adjunto captura de pantalla y el log de errores.**

![estados](https://cloud.githubusercontent.com/assets/17443346/13624891/e4d71a58-e590-11e5-9a3e-27965ca3accd.jpg)


[Wed Mar 09 00:31:30.091674 2016] [access_compat:error] [pid 983534:tid 140648747304704] [client 167.250.5.11:51173] AH01797: client denied by server configuration: /home2/ph/public_html/app/etc/local.xml
[Wed Mar 09 00:31:25.326392 2016] [access_compat:error] [pid 983646:tid 140648820733696] [client 167.250.5.11:51171] AH01797: client denied by server configuration: /home2/ph/public_html/app/etc/local.xml
[Wed Mar 09 00:04:20.452822 2016] [access_compat:error] [pid 930681:tid 140648852203264] [client 167.250.5.11:50307] AH01797: client denied by server configuration: /home2/ph/public_html/app/etc/local.xml
[Tue Mar 08 23:54:32.899108 2016] [access_compat:error] [pid 929312:tid 140648873182976] [client 167.250.5.11:49869] AH01797: client denied by server configuration: /home2/ph/public_html/app/etc/local.xml
[Tue Mar 08 23:54:15.689726 2016] [access_compat:error] [pid 929312:tid 140648757794560] [client 167.250.5.11:49858] AH01797: client denied by server configuration: /home2/ph/public_html/app/etc/local.xml
[Tue Mar 08 23:48:20.498261 2016] [access_compat:error] [pid 929312:tid 140648831223552] [client 167.250.5.11:49584] AH01797: client denied by server configuration: /home2/ph/public_html/app/etc/local.xml
[Tue Mar 08 23:48:10.776854 2016] [access_compat:error] [pid 930681:tid 140648789264128] [client 167.250.5.11:49582] AH01797: client denied by server configuration: /home2/ph/public_html/app/etc/local.xml
[Tue Mar 08 23:47:58.689309 2016] [access_compat:error] [pid 929396:tid 140648820733696] [client 167.250.5.11:49574] AH01797: client denied by server configuration: /home2/ph/public_html/app/etc/local.xml
[Tue Mar 08 23:47:14.460635 2016] [access_compat:error] [pid 929368:tid 140648820733696] [client 167.250.5.11:49563] AH01797: client denied by server configuration: /home2/ph/public_html/app/etc/local.xml

Quedo a su disposición para cualquier otra información que necesiten. Saludos.

**Comment by fcapua-summa** [comment]
Hola @pabloigrana 

Te cuento que hemos subido una versión actualizada del plugin el cual debería cubrir los puntos anteriormente mencionados, puedes descargarla aquí: https://github.com/mercadopago/cart-magento/tree/2.1.6

Respecto a la impresión de la oblea, la diferencia se debe al tipo de impresión que tenia por defecto el plugin, ahora hemos agregado una configuración en el admin para que puedas elegir que formato es el que deseas.

Saludos!
