### ISSUE TITLE
Resumen de pago incorrecto

### ISSUE THREAD

**Issue by desarrollo-rollpix** [mercadopago/cart-magento#106]
Hola a todos,

Tengo el siguiente problema al llegar a MP desde una tienda Magento.
Cuando realizo un pedido con más de un item, al llegar a MP no veo el resumen correctamente. Sólo aparece el nombre de uno de los productos sin embargo el **Monto** tiene sumado todos los items. A su vez, el costo de envío no está detallado aunque si se suma al **Total**, lo cuál puede ser confuso de cara al usuario (Como también comentar en #104).
Les dejo unas capturas para que se entienda mejor el problema que estoy teniendo.

Gracias

![1_carro](https://cloud.githubusercontent.com/assets/12416775/13461241/01292f66-e05f-11e5-990a-111441bec736.png)
![2_checkout](https://cloud.githubusercontent.com/assets/12416775/13461240/012928d6-e05f-11e5-97f1-50dff60046ec.png)
![3_mp](https://cloud.githubusercontent.com/assets/12416775/13461239/0128b69e-e05f-11e5-9fdc-0019db088bb1.png)

**Comment by fcapua-summa** [comment]
Hola @desarrollo-rollpix,
Lamentablemente la integración standard tiene esa limitante visual, ya que no es un problema con el cálculo de los costos.
Si queres esa lógica se puede modificar en el archivo **1.6.x-1.9.x/app/code/community/MercadoPago/Core/Model/Standard/Payment.php:105**:
```php
protected function getItems($order)
    {
        $items = [];
        foreach ($order->getAllVisibleItems() as $item) {
            $product = $item->getProduct();
            $image = (string)Mage::helper('catalog/image')->init($product, 'image');

            $items[] = [
                "id"          => $item->getSku(),
                "title"       => $product->getName(),
                "description" => $product->getName(),
                "picture_url" => $image,
                "category_id" => Mage::getStoreConfig('payment/mercadopago/category_id'),
                "quantity"    => (int)number_format($item->getQtyOrdered(), 0, '.', ''),
                "unit_price"  => (float)number_format($item->getPrice(), 2, '.', '')
            ];
        }

        return $items;
    }
```

Este es el método encargado de armar el detalle de cada ítem, una posible solución es que en vez de enviar el nombre completo del producto envies algo más genérico.

**Comment by desarrollo-rollpix** [comment]
Ok gracias, voy a probar de esa forma.

**Comment by ferluna3010** [comment]
hola, estoy utilizando el modulo de Mercado Pago para WooCommerce, como deberia hacer para que en el detalle del checkout solamente aparezca algo mas general como por ejemplo "Pedido web numero 1234" y una imagen del logo de mi web. Es decir que no salga el articulo y foto del mismo.
Agradeceria su colaboracion o alguna linea de codigo, ya que tengo minimos de programacion
