### ISSUE TITLE
Nueva Orden

### ISSUE THREAD

**Issue by emontielm** [mercadopago/cart-magento#109]
Hola. Instale el modulo, lo configure y realice pruebas y si pasan las compras, solo tengo dos problemas:
 
1) No llegan los correos de new order después de cada compra. 
2) Ademas de que todos los pedidos se quedan en pendiente. Sera porque estoy en modo Sandbox?

**Comment by fcapua-summa** [comment]
Hola @emontielm ,

1) ¿Qué versión de Magento estás corriendo? En las últimas versiones los emails de nueva orden salen mediante un cron. Para más información podes chequear este link: http://magento.stackexchange.com/questions/49935/new-order-email-notification-not-working

2) La URL del sitio es de acceso público. MercadoPago te va a enviar una notificación con los cambios de estado de la orden. También puede ser que tengas que configurar a que estado queres que pase en las diferentes instancias, esto lo haces de **System > Configuration > Sales > Payment Methods > MercadoPago - Global Configuration**

Gracias!

**Comment by emontielm** [comment]
Hola. 

Mi version es Magento versión 1.8.0.0.
y estas son las configuraciones que tengo.

![captura](https://cloud.githubusercontent.com/assets/12701775/13612682/4f70bf80-e52e-11e5-8a58-5af0469e2499.png)

Cuando pasa el pago por medio de tarjeta de crédito o débito me regresa al success page. Tanto si se denegó el pago o si se realizo correctamente, en Magento la orden sigue en "pending".

Se tiene que programar la parte de cancelar orden si la compra fallo.?
Por que se queda en pendiente a pesar que me dijo que si se realizo la compa?

**Comment by fcapua-summa** [comment]
Hola @emontielm,

Te hago algunas consultas para entender mejor el inconveniente que estás teniendo:

- ¿La URL en donde estás probando se puede acceder desde cualquier lado? MercadoPago necesita poder acceder a la URL para poder notificarte del cambio de estado de los pagos.
- Respecto al envio de emails, ¿el resto de los emails te andan de forma correcta (nueva cuenta, recupero de contraseña, etc)?
- ¿Estás utilizando la implementación de checkout standard o custom?

Gracias!

**Comment by emontielm** [comment]
Sí, la url es accesible desde cualquier lado.
Sí, los otros email funcionan perfectamente.
El Checkout es un One Step Checkout

**Comment by emontielm** [comment]
Ya lo pude resolver.

Hola

Ya puede resolver los 2 problemas que tenia:

1) Habilite los log de MercadoPago.
Cuidado con los permisos que puedan tener los archivos en var/log/; 
mercadopago-custom.log, mercadopago-notification.log y mercadopago-standard.log

2) Me di cuenta que tenían errores y eran por la versión PHP que se manejaba en el servidor (5.3); principalmente por el manejo de los arrays y sus declaraciones( De "[ ]" a "array()" ).

Con estos cambios se resolvieron los 2 problemas.

Gracias @fcapua-summa por la guía.

**Comment by fcapua-summa** [comment]
Me alegro que se hayan solucionado los problemas!
