### ISSUE TITLE
Estatus pendiente

### ISSUE THREAD

**Issue by AlexSalas** [mercadopago/cart-magento#110]
Buenos días! Tengo un problema con la integración de MercadoPago en Magento 1.8.0.0 Estoy probando el pago con tarjeta en Modo Sandbox y sucede lo siguiente:

Realizo una compra con las tarjetas de prueba y el nombre de la tarjeta APRO y la transacción es aprobada:

![image](https://cloud.githubusercontent.com/assets/17747889/13642457/348d06ec-e5e2-11e5-8ce8-e009185de5ef.png)

En el Admin tengo estas configuraciones:

![image](https://cloud.githubusercontent.com/assets/17747889/13642503/64627596-e5e2-11e5-871f-75fff230252d.png)

![image](https://cloud.githubusercontent.com/assets/17747889/13642541/8d896678-e5e2-11e5-8cae-80f47b67a49d.png)

Sin embargo el pedido se guarda como Pendiente:

![image](https://cloud.githubusercontent.com/assets/17747889/13642577/b195e6b8-e5e2-11e5-9f41-0262e8847afc.png)

![image](https://cloud.githubusercontent.com/assets/17747889/13642593/ca440be0-e5e2-11e5-95fa-74568bf08f08.png)

Esto pasa porque es una compra de prueba o algo esta mal? O bien me faltan configuraciones? También se envía como pendiente cuando el pago es rechazado, Adjunto pantallas

![image](https://cloud.githubusercontent.com/assets/17747889/13642767/6c3503be-e5e3-11e5-8913-ef282b566d62.png)

![image](https://cloud.githubusercontent.com/assets/17747889/13642797/85f962ae-e5e3-11e5-9c22-481d902c08ca.png)

Muchas gracias de antemano por su apoyo.

**Comment by fcapua-summa** [comment]
Hola @AlexSalas 

Te hago algunas consultas para entender mejor lo que está ocurriendo:
* ¿El sitio donde estás probando es accesible desde cualquier lado? (Dominio público)
* ¿Cuál de las soluciones provista por MercadoPago estás utilizando? ¿Checkout Standard o Customizado?
* ¿Puede adjuntarme una captura del detalle de la orden en el admin? Lo que más me interesa de esto es el detalle de las transacciones que ocurrieron

Gracias!

**Comment by AlexSalas** [comment]
Hola, claro que si, con mucho gusto

- El sitio si es de dominio público

- Estamos usando ambas, el problema se presenta en las 2 modalidades

- 
![image](https://cloud.githubusercontent.com/assets/17747889/13647922/e730fc86-e5fb-11e5-8544-eb429ef6d528.png)
![image](https://cloud.githubusercontent.com/assets/17747889/13647940/f83ecf62-e5fb-11e5-9386-98a740d1da90.png)

**Comment by emontielm** [comment]
Hola

Yo también tuve los mismos problemas de que no se actualizaban los pedidos y de paso no se enviaban los email de nueva orden y actualización de pedido. 

Lo resolví de la siguiente manera:

1) Habilite los log de MercadoPago.
 Cuidado con los permisos que puedan tener los archivos en var/log/; 
mercadopago-custom.log, mercadopago-notification.log y mercadopago-standard.log

2) Me di cuenta que tenían errores y eran por la versión PHP que se manejaba en el servidor (5.3); principalmente por el manejo de los arrays y sus declaraciones( De "[ ]" a "array()" ).

Con estos cambios se resolvieron los 2 problemas.

Espero que te ayude.

Gracias también @fcapua-summa por la guía.

**Comment by fcapua-summa** [comment]
Hola @AlexSalas, ¿me podrás indicar si el comentario de @emontielm te sirvió de ayuda para solucionar los problemas?

Gracias!

**Comment by fcapua-summa** [comment]
Hola @AlexSalas, ¿sigues con problemas o han sido solucionados?

Saludos!

**Comment by AlexSalas** [comment]
Hola @fcapua-summa, disculpa la tardanza de mi respuesta, si, efectivamente el comentario de @emontielm me ayudó a resolver mi problema.

Muchísimas gracias!!!

**Comment by fcapua-summa** [comment]
Me alegro!
