### ISSUE TITLE
No envía copia de nueva orden al admin

### ISSUE THREAD

**Issue by emontielm** [mercadopago/cart-magento#112]
Hola chicos, aquí molestando de nuevo, estoy teniendo el siguiente problema. 

Cuando se realiza una compra exitosa sí se envía al cliente el email de nueva orden y actualización de la orden. Tengo configurado para que envié copia de la nueva orden a un correo ( al administrador). Sin embargo, no llegan los correos. En los otros métodos de pagos si llegan los correos al administrador.

Cheque los logs de Mercadopago y de Magento y no me notifican ningún error.

¿El modulo si envía los mensajes al administrador o esta parte se tiene que programar?

Estoy probando la ultima versión del modulo con Magento 1.8.0.0

Gracias por su atención.

**Comment by fcapua-summa** [comment]
@emontielm Lo revisamos y te avisamos.

Gracias!

**Comment by emontielm** [comment]
Hola, gracias por atenderme. Nota: también configure para que envié el correo de factura y ese si llega.

**Comment by fcapua-summa** [comment]
Hola @emontielm , ¿tienes instalada la última versión del plugin? 

No hemos podido reproducir este problema, ¿cómo tienes configurado para que envie la copia de la nueva orden?

**Comment by emontielm** [comment]
Hola. Así tengo la configuración

![factura2](https://cloud.githubusercontent.com/assets/12701775/13991649/a434749c-f0de-11e5-922d-cfd234887d97.png)

**Comment by fcapua-summa** [comment]
@emontielm, 
Hemos realizado pruebas configurando de la misma manera que nos indicas y no hemos tenido problemas en recibir la copia del email de nueva orden.

Te aconsejo que revises lo siguientes puntos:
- Tener instalada la última versión del plugin 2.1.5
- Revisar que no te haya llegado como spam en la cuenta
- Chequear que no esté teniendo conflictos con alguna otra extensión que tengas instalada

**Comment by fcapua-summa** [comment]
Hola @emontielm , ¿sigues con el problema o podemos dar por cerrado el issue?

Saludos!

**Comment by fcapua-summa** [comment]
Hola @emontielm, dado que no hemos recibido respuesta de tu parte, damos por cerrado el issue.

Si el problema persiste o tienes algún otro sentite libre de crear un nuevo issue.

Saludos!
