### ISSUE TITLE
Pedido com pagamento recusado status cancelado o estoque não retorna

### ISSUE THREAD

**Issue by kinfoxx** [mercadopago/cart-magento#113]
Olá, temos o modulo e estamos enfrentando um problema quando temos um pedido com pagamento rejeitado, na configurações do modulo colocamos para os recusados cancelar e nas configurações do magento esta habilitado para estornar estoque quando o pedido for cancelado, porem não ocorre o retorno do estoque quando temos um pedido recusado, alguém pode nos ajudar ?

**Comment by gmatsuoka** [comment]
Olá, tudo bem?

Como esta a configuração de status de pagamento <> pedidos? Pois, quando é enviado uma notificação automática de pagamento o módulo atualiza automaticamente o status do pedido que foi configurado.

Atenciosamente,

**Comment by kinfoxx** [comment]
Olá, tudo bem sim e você ? 

A configuração está para cancelar quando o pagamento é recusado, quando uma compra é recusada o status passa para cancelado, porem o produto sai do estoque e não retorna quando se cancela, na configuração do magento esta habilitado a opção para retornar ao estoque quando o pedido é cancelado.

**Comment by gmatsuoka** [comment]
Estou bem, obrigado.

O módulo apenas altera o status para o que foi configurado, não cancela o pedido efetivamente. Caso cancelasse não seria possível atualizar para outro status depois, isso impactaria o caso dos pagamentos que são rejeitados e logo em seguida aprovados. (exemplo: http://goo.gl/lqhN3r)

**Comment by gmatsuoka** [comment]
Olá,

Caso queira testar uma versão (ainda não oficial) do ajuste que retorna os itens para o estoque:

https://github.com/imasson/cart-magento/blob/summa_master/1.6.x-1.9.x/app/code/community/MercadoPago/Core/Model/Core.php

Atenciosamente,

Gabriel.

**Comment by fcapua-summa** [comment]
Olá @kinfoxx ,

O problema persiste?

**Comment by esavignone** [comment]
Por favor reabrir se o problema persistir.

Obrigado,
