### ISSUE TITLE
Nao abre o formulário de cartões no checkout

### ISSUE THREAD

**Issue by gerbesf** [mercadopago/cart-magento#114]
Notice: Undefined index: mercadopago_custom  in /app/code/community/MercadoPago/Core/Model/Custom/Payment.php on line 88

**Comment by fcapua-summa** [comment]
Faça o download da versão mais recente do plug-in aqui: https://github.com/mercadopago/cart-magento/tree/2.1.6

Se o problema persistir, por favor, dê detalhes sobre como você tiver configurado o plugin:
- Que tipo de check-out está habilitada (padrão ou personalizado)?
- São as credenciais de teste ou produtiva?
- Você vê alguma informação adicional nos logs?
