### ISSUE TITLE
Fatal error: Call to a member function getData() on a non-object in /home/.../app/code/community/MercadoPago/Core/Model/Standard/Payment.php on line 188

### ISSUE THREAD

**Issue by JonaPolo** [mercadopago/cart-magento#115]
Hola, soy nuevo en esto y necesito alguien me ayude, instale mercado pago a magento 1.9 tal y conforme las indicaciones, pero tengo errores que no se porque son. 

1. Al momento de pagar elijo MercadoPago, le doy continuar y no me abre ninguna ventana, ni opcion de pago, ni nada para elegir (cuotas, nro tarjeta, etc, o cosas por el estilo), luego doy siguiente, me muestra el resumen y al final cuando le doy pagar me tira este error:

 Fatal error: Call to a member function getData() on a non-object in /home/aventas15/public_html/ventas/app/code/community/MercadoPago/Core/Model/Standard/Payment.php on line 188

Nose que estoy haciendo mal, alguien que me ayude, graciassssss

**Comment by fcapua-summa** [comment]
Hola @JonaPolo , eso que comentas suena a estar relacionado con un bug que hemos solucionado en la última versión del plugin: https://github.com/mercadopago/cart-magento/tree/2.1.6

Te sugiero que actualices el plugin y me confirmes si soluciona el problema o si corresponde a otra cosa.

Saludos!

**Comment by JonaPolo** [comment]
Hola gracias por contestar, mira acabo de actualizar los archivos con todos los bugs (completos) y nuevamente realizo la prueba de compra y me tira el mismo error, Fatal error: Call to a member function getData() on a non-object in /home/../ventas/app/code/community/MercadoPago/Core/Model/Standard/Payment.php on line 159

Solo que ahora me cambio el nro de linea, necesito me ayudennn ...graciassss

Ah otra cosa cuando elijo Argentina como en la config. global, en custom checkout no me aparece la imagen con los logos de las tarjetas (como en el ejemplo de configuracion).

**Comment by esavignone** [comment]
Hola JonaPolo,

Vamos a estar revisando el error reportado.

Con respecto a la imagen del Checkout, es un link externo, no podemos reproducir el problema, te sucede con todos los browsers?

Saludos!

**Comment by fcapua-summa** [comment]
Hola @JonaPolo ,

Te pido que actualices a la última versión del plugin: https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x

Y nos avises si el problema persiste.

Saludos!

**Comment by JonaPolo** [comment]
Hola Facundo, actualice y me funciono la compra, el unico problema ahora es
que al darle continuar (al terminar la compra, sea por lighbox o
redireccionado) me tira este error:

*Fatal error*: Class 'MercadoPago_Core_Block_AbstractSuccess' not found in
*/home/.../ventas/app/code/community/MercadoPago/Core/Block/Standard/Success.php*
on
line *4*

*Me falto algo??*

*Gracias,*

*Jonathan*



El 22 de abril de 2016, 15:27, Facundo Capua <notifications@github.com>
escribió:

> Hola @JonaPolo <https://github.com/JonaPolo> ,
>
> Te pido que actualices a la última versión del plugin:
> https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x
>
> Y nos avises si el problema persiste.
>
> Saludos!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mercadopago/cart-magento/issues/115#issuecomment-213542695>
>



-- 
Jonathan S. Polo V.
-------------------------------
Skype: Jonathan.Polo

**Comment by JonaPolo** [comment]
Hola, alguna novedad para solucionar este problema que aun lo sigo teniendo
y no puedo usar mercadopago como forma de pago. Gracias

2016-04-22 17:56 GMT-03:00 Jonathan Polo Velezmoro <tecjpolo@gmail.com>:

> Hola Facundo, actualice y me funciono la compra, el unico problema ahora
> es que al darle continuar (al terminar la compra, sea por lighbox o
> redireccionado) me tira este error:
>
> *Fatal error*: Class 'MercadoPago_Core_Block_AbstractSuccess' not found
> in
> */home/.../ventas/app/code/community/MercadoPago/Core/Block/Standard/Success.php* on
> line *4*
>
> *Me falto algo??*
>
> *Gracias,*
>
> *Jonathan*
>
>
>
> El 22 de abril de 2016, 15:27, Facundo Capua <notifications@github.com>
> escribió:
>
>> Hola @JonaPolo <https://github.com/JonaPolo> ,
>>
>> Te pido que actualices a la última versión del plugin:
>> https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x
>>
>> Y nos avises si el problema persiste.
>>
>> Saludos!
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mercadopago/cart-magento/issues/115#issuecomment-213542695>
>>
>
>
>
> --
> Jonathan S. Polo V.
> -------------------------------
> Skype: Jonathan.Polo
>



-- 
Jonathan S. Polo V.
-------------------------------
Skype: Jonathan.Polo

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by fcapua-summa** [comment]
Hola @JonaPolo , ¿agregaste todos los archivos de la extensión?

En particular te está dando un error como si faltara el archivo que se encuentra en **app/code/community/MercadoPago/Core/Block/AbstractSuccess.php**
¿Este archivo lo tienes correctamente instalado?

**Comment by esavignone** [comment]
Hola @JonaPolo, 

Alguna novedad sobre este tema? 

Saludos,

**Comment by esavignone** [comment]
Hola @JonaPolo ,

El ticket será cerrado, por favor reabrir si el problema persiste.

Muchas gracias!
