### ISSUE TITLE
Error en la suma de las dimensiones - alto - ancho y longitud 

### ISSUE THREAD

**Issue by echi22** [mercadopago/cart-magento#117]
Hola, tengo instalado el plugin y funciona todo bien salvo por el tema de que al comprar más de un producto se produce un error al calcular el tamaño de los mismos y por ende no puedo enviarlo usando mercadoenvios.

Para entender mejor lo que quiero decir voy a poner un ejemplo:
-Supongamos que tengo el producto "A" cuyas dimensiones son 50*20*20.
-Si el cliente selecciona una unidad del producto "A", no hay problema porque está dentro de las medidas previstas por OCA.
-Si el cliente selecciona dos unidades del producto "A", el sistema suma las tres dimensiones y calcula como si el tamaño fuese de 100*40*40. Al tener uno de los tres parametros mayores a 70, MercadoEnvios no puede enviarlo. Sin embargo este calculo no está bien, xq por ejemplo ubicando un producto al lado de otro el tamaño sería de 50*20*40 y tendrían que poder enviarse los productos.

Se entiende el problema?? Podrán darle alguna solución?

**Comment by gmatsuoka** [comment]
Hola @echi22, 
Vamos analizar este caso. Muchas Gracias!

**Comment by echi22** [comment]
Hola @gmatsuoka yo creo que lo resolví pero tal vez vos puedas confirmarme si la solución es correcta o resolverlo de una manera más eficiente.

Por lo que estuve probando, entiendo que el precio del envío se calcula a partir del volumen del paquete y de su peso. Sin embargo la api requiere que se le envíen los datos de alto, ancho y largo.

Mi solución fue calcular el volumen de cada elemento que debe ser enviado, luego sumar estos valores para obtener el volumen total y finalmente calcular los valores de alto, ancho y largo que den como resultado el volumen total que había calculado previamente. 

Dejo un  ejemplo para que se entienda con mayor claridad:

Supongamos que tengo lso productos A, B Y C con las siguientes dimensiones:
-A: 30 x 15 x 20
-B: 50 x 20 x 18
C: 17 x 17 x 17

 El primer paso sería calcualr los volumenes:
- Volumen A: 30 x 15 x 20 = 9000
- Volumen B: 50 x 20 x 18 = 18000
- Volumen C: 17 x 17 x 17 = 4913

-Volumen total: 31913

Una vez obtenido el volumen total, calculo la raiz cúbica para obtener el valor de las tres dimensiones que coincida con el volumen total:

- 31913 ^(1/3) = 31,72

De esta forma el valor enviado a la api de mercadoenvios será 32 x 32 x 32. Si bien estos no son los valores reales que deberá tener el paquete, el monto que debe abonar el cliente aparentemente es el correcto. 

Si podés comentame si te parece correcto o si ves algún fallo.

Ezequiel

**Comment by mroffe** [comment]
Y suponiendo que envío tal cantidad de productos que entran en 2 o mas paquetes. El método de envío no calcula el valor de los dos o mas paquetes?. Sumado a esto, no debería generar dos o mas etiquetas o nros de tracking?. Hasta hoy si supera los 70cm da error.

**Comment by esavignone** [comment]
Hola @mroffe,

Este bug está solucionado en el siguiente branch (https://github.com/imasson/cart-magento/commits/support_637_3), todavía no se encuentra en la versión pública.

Saludos,

**Comment by esavignone** [comment]
La solución fue proporcionada en el comentario anterior, por favor, reabrir si el problema persiste.

Muchas gracias!

**Comment by cristianoap** [comment]
Hola, tengo un problema acerca de esa solución. Estoy intentando añadir mi zipcode en el carrito (CEP brasileño), pero he recibo un error y no es posible obtener los métodos de envío. Yo edité el codigo e así yo descubrí que las dimensiones enviadas para la API son 8x8x8,200 y el producto tíene L(11), A(2), C(11) y W(200). Estos son las medidas oficiales minimas de el Correios. No sé si eso esta relacionado pero no puedo comprar con MercadoEnvios, recibo el error **{"status":400,"response":{"message":"Invalid dimension values.","error":"invalid_shipments","status":400,"cause":[]}}**
