### ISSUE TITLE
Estados de pedidos/Impresión de etiquetas

### ISSUE THREAD

**Issue by pabloigrana** [mercadopago/cart-magento#119]
Qué tal chicos, les muestro lo siguiente para corroborar si esto es un error de la extensión o qué...
Estoy probando la nueva extensión en dos instalaciones distintas, una está corriendo sobre Magento 1.9.2.3 y otra sobre 1.9.2.4 y con una extensión de OSC.
Siempre probando con checkout classic y en ambas tengo problemas con el estado de los pedidos, o tal vez ustedes me digan que es el funcionamiento normal y yo no estoy entiendo como trabaja Magento...

**Instalación Magento 1.9.2.3 sin OSC**

![image](https://cloud.githubusercontent.com/assets/17443346/14407048/5bf978b0-fe91-11e5-8573-cfc7cd605e9a.png)

1. Realicé el pago y en el back automáticamente el estado es COMPLETO a pesar de haberlo seteado como PROCESANDO desde la configuración.

![image](https://cloud.githubusercontent.com/assets/17443346/14407022/73b0bece-fe90-11e5-90ed-f05c8f5b66d2.png)

En cambio en la instalación de **Magento 1.9.2.4 con extensión OSC activada y también actividada en la configuración de MP** el estado queda en PROCESANDO, pero después no encuentro la manera de pasarlo a COMPLETO ¿? Cuándo debería pasar a COMPLETO? O cómo sería la pregunta!

![image](https://cloud.githubusercontent.com/assets/17443346/14407299/95024c38-fe99-11e5-91e9-3a2ea90bb0a3.png)

_Procesando_

![image](https://cloud.githubusercontent.com/assets/17443346/14407183/eb88ab32-fe95-11e5-8e3d-388229341610.png)

_Información de pedido_

![image](https://cloud.githubusercontent.com/assets/17443346/14407186/11bcaac4-fe96-11e5-9d86-d38167167b28.png)

_Historial de comentarios_

![image](https://cloud.githubusercontent.com/assets/17443346/14407193/456dbcf0-fe96-11e5-9d41-20a414a83a33.png)

Cómo paso a estado completo el pedido? Selecciono la opción enviar?

Si bien el pedido fue enviado según el historial, y se generó el número de seguimiento aquí no figura que haya sido enviado.

![image](https://cloud.githubusercontent.com/assets/17443346/14407224/35abd36e-fe97-11e5-924f-c10e44335b51.png)

En cambio en el primer caso sí queda registrado aquí el envío.

![image](https://cloud.githubusercontent.com/assets/17443346/14407359/4ceb450a-fe9c-11e5-9f02-e50106842fd1.png)

Desde información de pedido no puedo cambiar el estado, solo figura procesando.

![image](https://cloud.githubusercontent.com/assets/17443346/14407207/aa6320fa-fe96-11e5-9179-8f2e48b9e3c2.png)

Si selecciono ENVIAR, me genera un envío nuevo y ahí si luego queda en COMPLETO, pero me quedan asociados dos envíos al producto, entiendo que no es lo correcto.

![image](https://cloud.githubusercontent.com/assets/17443346/14407089/cd4da832-fe92-11e5-8dcf-3e8074710e30.png)

![image](https://cloud.githubusercontent.com/assets/17443346/14407233/bf69b7f6-fe97-11e5-9fee-abd1131fe0dd.png)

**Cuáles deberían ser los pasos correctos y lógicos de un pedido con pago aprobado y acreditado?? Es correcto que los envíos se generen automáticamente o uno debería tener que seleccionar la opción ENVIAR en la solapa superior? O para poner un pedido en completo uno debería poder modificar el estado desde el historial, que en mi caso solo figura procesando?**

### Otro problema:

Esta opción genera un PDF vacío para descargar, entiendo que si uno selecciona varios pedidos simultáneos debería generar la descarga de cada etiqueta individualmente no cierto?

![image](https://cloud.githubusercontent.com/assets/17443346/14407169/7d91f2be-fe95-11e5-8592-b917bac6e812.png)

Cualquier duda respecto a lo comentado me avisan que voy a tratar de aportar los datos que necesiten.
Saludos.

**Comment by esavignone** [comment]
Hola pabloigrana,

Vamos a estar revisando los casos en detalle.

Por lo que veo, el caso de **Magento 1.9.2.4 con extensión OSC activada ** donde el pedido queda en estado PROCESANDO y no se puede pasar a COMPLETO, no habría ningún problema con el Plugin, parece estar más relacionado con el flow de estados propio de la implementación.

Te mantenemos al tanto.

Saludos,

**Comment by pabloigrana** [comment]
Ok, perfecto, justo estaba escribiendo esto, es otro caso con Magento 1.9.2.4 pero deshabilité el OSC de la extensión y de MP, misma configuración de estados:

Realizo un pago satisfactorio con TC, esto figura en el historial del pedido:

![image](https://cloud.githubusercontent.com/assets/17443346/14412064/05262fd4-ff30-11e5-83cb-a901ac6aadd6.png)

Sin embargo el pedido queda con el estado de pendiente:

![image](https://cloud.githubusercontent.com/assets/17443346/14412135/bc6abb28-ff31-11e5-9c82-87268b60c31d.png)

Se generó el envío, puedo imprimir la etiqueta, etc, pero queda como pendiente...

Saludos

**Comment by imasson** [comment]
Hola pabloigrana,

En magento las ordenes pasan a Complete cuando tienen sus correpondientes shipment e invoice creados. Esto, en caso de que utilize MercadoEnvios, se realiza automaticamente por el plugin mediante las notificaciones.
El flujo en el historial de comentarios deberia ser asi para una orden con MercadoEnvios:
![image](https://cloud.githubusercontent.com/assets/8289723/14431549/88d1613a-ffdc-11e5-8fa2-62c496111fbe.png)
En este caso tambien tenia configurado como Processing para los pedidos Aprobados.
Como se ve en el historial primero se aprueba el pago y la orden pasa a Processing, luego a Complete cuando se crea el shipment.

Con respecto a la etiqueta de envio: 
Para imprimir la correspondiente a MercadoEnvios debes dirigirte a la seccion Shipments dentro del detalle de la orden

![image](https://cloud.githubusercontent.com/assets/8289723/14431832/dbbc22a8-ffdd-11e5-9cb8-922f3cd5b176.png)

Y luego dentro del detalle del shipment particular se puede descargar el pdf o el zip dependiendo de la configuracion:

![image](https://cloud.githubusercontent.com/assets/8289723/14431878/0ec5a5de-ffde-11e5-8aa8-1b4d8f2f46dc.png)

Saludos!

**Comment by pabloigrana** [comment]
Qué tal @imasson , gracias por la aclaración sobre cómo debería ser el flujo normal de estados cuando uno utiliza MercadoEnvíos.
Mi confusión surge dado que cada pago que hago (todos aprobados y acreditados) terminan quedando con estados diferentes... A veces en completo, otras en pendiente y otras en procesando como se puede apreciar en las capturas y nunca lograba entender cuál debería ser el flujo correcto. 

Respecto al tema etiquetas, me refería puntualmente a la pantalla general de pedidos ya que es donde existe la opción de selección múltiple de pedidos y se pueden mandar a imprimir todas las etiquetas juntas, sin tener que hacerlo individualmente una por una.

Pregunta, el issue sigue abierto porque se está revisando el flow de estados propio de la implementación como mencionó @esavignone no cierto? O sos parte del equipo que se encargó de la revisión y tu aclaración es para informarme que está funcionando todo bien? 

Gracias nuevamente y saludos!

**Comment by imasson** [comment]
Hola @pabloigrana!
El flujo de estados que te menciono es el que hemos podido reproducir en multiples ejemplos con la version actual del plugin. Por lo tanto en tu caso deberia funcionar de la misma forma. Si persiste el problema por favor envianos los logs del plugin para tratar de determinar el origen del problema. Y tambien la version de plugin que estas utilizando.

Con respecto a la impresion de etiqueta, la funcionalidad de impresion bulk incorporada con magento no esta integrada con el plugin, por lo cual para ordenes con MercadoEnvios deberias descargar la etiqueta de cada shipment en forma individual.

Saludos! seguimos en contacto.

**Comment by pabloigrana** [comment]
Qué tal @imasson , estuve probando y me di cuenta que el conflicto con los estados era generado por la extensión Store Maintenance, la cual tenía deshabilitida, pero así y todo generaba problemas, una vez desinstalada el flujo de estados es como indicaste vos.

Tengo dos preguntas, cuando cancelo una venta, si bien el estado se pasa a CANCELADO, el resto de los campos no sufre ninguna actualización, así trabaja la extensión?
![image](https://cloud.githubusercontent.com/assets/17443346/14481079/c3acb546-0105-11e6-91d1-5ec4c2354a7f.png)

Y la otra es respecto a la extensión OSC que uso en el sitio. Compatible con MercadoPago/MercadoEnvíos evidentemente es, porque funciona todo bien con ambos servicios habilitados. El problema que tengo es que mientras tengo MercadoEnvíos habilitado, no puedo ingresar a la solapa de configuración de OSC, arroja el siguiente error:

Fatal error: Call to a member function getAllItems() on a non-object in /home/xxxxxxx/public_html/test/app/code/community/MercadoPago/MercadoEnvios/Model/Shipping/Carrier/MercadoEnvios.php on line 88

Puedo tener habilitado los ocho servicios de envío que vienen con Magento y no hay ningún problema, solo con MercadoEnvíos pasa. Es algo relacionado con ME?

Saludos!

**Comment by imasson** [comment]
Hola @pabloigrana me alegro que te haya funcionado bien.

Con respecto al estado cancelado, es así el funcionamiento de la extensión. 
En una próxima versión se agrega la creación de credit memo y retorno de stock, para cuando el pago es refunded.

Y sobre el error de OSC, intentaremos reproducir el problema y notificar sobre algún avance en el mismo lo antes posible.

Saludos!

**Comment by pabloigrana** [comment]
Qué tal @imasson , gracias por responder la inquietud, me confirmarías cuáles de los 4 logs necesitan para analizar el flujo de los estados? Estoy viendo que algunos contienen datos de la cuenta... En caso de necesitar todos, te pido que me indiques un correo donde mandarlos o algún medio.

![image](https://cloud.githubusercontent.com/assets/17443346/14575601/2abe3a7c-0339-11e6-8b2e-927fee9f7b65.png)

Como se aprecia en la captura, el flujo es pendiente -> completo -> procesando
por lo tanto otra vez me están quedando en procesando...

![image](https://cloud.githubusercontent.com/assets/17443346/14575699/ecfcf272-0339-11e6-9124-22accdff3206.png)
![image](https://cloud.githubusercontent.com/assets/17443346/14575702/f2c06626-0339-11e6-9ce8-95e5a089f60e.png)

Tal vez tenga que ver con el error que detallé en el post anterior?
Saludos!

**Comment by esavignone** [comment]
Hola @pabloigrana, 

Seguís con el mismo error? El bug está solucionado en la última versión del plugin.

Saludos,

**Comment by pabloigrana** [comment]
Qué tal @esavignone, no realicé más pruebas porque estaba esperando una confirmación de ustededes. Había visto que sacaron una una nueva versión pero pensé que corregía otras cosas...
Descargo la siguiente versión no cierto?
https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x 

Gracias!

**Comment by esavignone** [comment]
Como estás @pabloigrana? Exacto, esa versión debería solucionar tu problema.

Quedamos a la espera de tu feedback.

Saludos,

**Comment by pabloigrana** [comment]
Qué tal @esavignone, instalé la nueva versión. Solucionado el problema respecto a la pantalla de configuración del OSC que cuando estaba activado MercadoEnvíos me quedaba la pantalla en blanco. Hice una sola transacción con TC, la misma quedó en COMPLETO. Se generó el envío, etiqueta, aparentemente todo bien. Lo único que me llama la atención es el flow de estados ya que se generaron tres "procesando":

![image](https://cloud.githubusercontent.com/assets/17443346/15729884/67bfd014-283e-11e6-8703-07aea575002f.png)

Te dejo esa inquietud y de paso te pregunto, si es que ustedes se encargan del desarrollo, si hay alguna fecha estimativa para que salga la full api de Mercado Envíos, ya que tengo entendido de eso depende para que habiliten el envío a sucursal Oca.
Gracias!
