### ISSUE TITLE
Pedido fechando com o frete zerado

### ISSUE THREAD

**Issue by Rafaelmax** [mercadopago/cart-magento#120]
Ola na loja que estou utilizando o modulo de vocês, o transparente me cobra o valor de frete normal o checkout custom, porem o pagamento pelo normal ao qual abre a pagina do mercadopago e paga pelo ambiente deles não está cobrando o valor do frete está zerando ele sendo que na pagina de checkout ele mostra o valor do frete sendo setado e mostra o valor no total, notei que só acontece com o módulos de vocês os demais fecha com o valor de frete correto poderiam verificar e me passar alguma solução

**Comment by esavignone** [comment]
Oi Rafaelmax,

Estaremos analisando o problema.

Atenciosamente,

**Comment by gmatsuoka** [comment]
Olá Rafael, tudo bem?

Você pode passar algumas informações sobre esse erro?
- Url do site
- Passo a passo para gerar o erro
- Printscreen

Gabriel.

**Comment by Rafaelmax** [comment]
É uma loja Magento segue https://www.goldenclasssemijoias.com.br

para gerar o erro faça uma compra acima de 80 reais e selecione o frete qualquer um dos dois valores PAC ou Sedex, verá que após a confirmação do pedido na tela de pagamento do Mercado Pago ele deixa sem o valor do frete na comprar

segue print do checkout e da tela de pagamento

![print1](https://cloud.githubusercontent.com/assets/18387505/14437852/9a9980ce-fff9-11e5-921f-55bb5f4f21d3.jpg)
![print2](https://cloud.githubusercontent.com/assets/18387505/14437858/a022d2e8-fff9-11e5-906a-e8c1897e836e.jpg)

**Comment by Rafaelmax** [comment]
Boa noite,

então Gabriel foi isso mesmo, baixei o modulo antes dessa correção, eu atualizei o código novamente e resolveu o problema obrigado!

**Comment by gmatsuoka** [comment]
Perfeito!

Qualquer duvida estamos a disposição.

Atenciosamente,

Gabriel.

**Comment by fcapua-summa** [comment]
Nós resolvemos esse problema, qualquer coisa pode ser reaberto
