### ISSUE TITLE
Imagem dando erro no SSL

### ISSUE THREAD

**Issue by kinfoxx** [mercadopago/cart-magento#121]
Olá, 

As imagens com os links https://content.mercadopago.com/fp/clear.png e https://jk96mpy0-0730f5a67fb32b9197a53a4ddbfa02fe3080285b-sac.d.aa.online-metrix.net/fp/clear.png?org_id=jk96mpy0&session=13456c131e9d664f4dd628cb8e4322bc&di=yes , esta gerando erro no SSL informando que o site é seguro em partes, procuramos esses links nos arquivos do modulo para alterarmos para um link interno e não achamos, pode nos informar onde encontro esses links no módulos para podermos alterar para um link interno?

Obrigado,

**Comment by gmatsuoka** [comment]
Olá, tudo bem?

Pode enviar algumas informações, por favor?
- Qual versão do módulo esta utilizando
- Link da Loja
- Print-screen do local onde esta ocorrendo o erro

Atenciosamente,

**Comment by kinfoxx** [comment]
http://www.kshopsa.com.br no checkout, percebi que somente pelo firefox que da, o cadeado fica com um erro , a versão do modulo é a ultima colocada para donwload aqui no github , 
![2016-04-12](https://cloud.githubusercontent.com/assets/17278554/14471504/518be72e-00c5-11e6-8cf7-51b539c3ecca.png)
![2016-04-12 1](https://cloud.githubusercontent.com/assets/17278554/14471549/7e47113a-00c5-11e6-9f65-54e0ae425232.png)

**Comment by kinfoxx** [comment]
Olá, a url do nosso site é www.kshopsa.com.br , conseguimos resolver o problema alterando o arquivo conforme informado pela issue #122 . Obrigado
