### ISSUE TITLE
Erro de Mixed Content na pagina de checkout

### ISSUE THREAD

**Issue by magnored** [mercadopago/cart-magento#122]
![image](https://cloud.githubusercontent.com/assets/7586874/14468715/522d6832-00b7-11e6-8b2f-28ef5f62d435.png)

Poderiam me dar uma ajuda com este erro. 
Tentei trocar a URL base no arquivo MercadoPago\OneStepCheckout\Block\Custom\Form.php
Inserindo HTTPS no script: <script src="https://ui.mlstatic.com/chico/tiny/0.1.1/tiny.min.js"></script>
Mas mesmo assim a mensagem de erro continua

**Comment by imasson** [comment]
Oi @magnored, você pode aplicar essa alteração a este arquivo, a alteração será incluída em uma nova versão.
Obrigado.

**Comment by magnored** [comment]
obrigado @imasson, ja removi e agora deu certo

**Comment by fcapua-summa** [comment]
Nós resolvemos esse problema, qualquer coisa pode ser reaberto
