### ISSUE TITLE
Erro no upgrade do módulo

### ISSUE THREAD

**Issue by ghayashi** [mercadopago/cart-magento#123]
Temos um cliente que está com problemas ao atualizar o módulo.

Cliente: **detonashop**
1. Upgrade MercadoPago executado conforme instruções:
```
If you have alread installed a previous version of the MercadoPago Plugin please follow the instructions:

    Delete the following files and directories from your current installation to ensure upgrade correct functionality (or execute commands detailed below).

    app/code/community/MercadoPago
    app/design/frontend/base/default/template/mercadopago
    app/design/adminhtml/default/default/template/mercadopago
    lib/mercadopago
    /app/locale/en_US/mercadopago.csv
    /app/locale/en_AR/mercadopago.csv
    /app/locale/en_CL/mercadopago.csv
    /app/locale/en_CO/mercadopago.csv
    /app/locale/en_ES/mercadopago.csv
    /app/locale/en_MX/mercadopago.csv
    /app/locale/en_BR/mercadopago.csv

Linux Commands:

$ rm -rf  app/code/community/MercadoPago
        app/design/frontend/base/default/template/mercadopago
        app/design/adminhtml/default/default/template/mercadopago
        lib/mercadopago

find . -name "mercadopago.csv" -type f -delete

```

2. Comportamento atual:
Erro ao tentar acessar as páginas administrativas para configuração do módulo Mercado Pago.

> **_ Fatal error: Call to a member function getAllItems() on null in /home/********/public_html/app/code/community/MercadoPago/MercadoEnvios/Model/Shipping/Carrier/MercadoEnvios.php on line 88_**

**Comment by ghayashi** [comment]
@fcapua-summa

**Comment by fcapua-summa** [comment]
Já resolvemos esse problema. Faça o download da versão mais atual do módulo a partir daqui https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x

**Comment by fcapua-summa** [comment]
Se o problema persistir, por favor nos informe:
* Tem MercadoEnvios habilitado?
* Qual opção de check-out (standard ou custom) esta habilitado?
* Em qual pagina do administrador ocorre esse erro?

**Comment by ghayashi** [comment]
Olá,

Pedirei para o cliente fazer e baixar novamente a versão do github.

O erro ocorre assim que o módulo é atualizado, atualiza os arquivos e quando tenta acessar a página administrativa para configurá-lo é retornado este erro na tela.
Não foi habilitado nenhum tipo de checkout, pois o erro ocorre ao tentar abrir está página de configuração.

**Comment by fcapua-summa** [comment]
Olá @ghayashi,
Enquanto não fomos capazes de reproduzir o problema, fizemos um ajuste que deve evitar o problema.
Peço que você atualizar o plugin para a versão recém-publicado: https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x

E você você nos informar se o problema persistir.

Thanks!

P.D: Peço desculpas para os Portugues pobres

**Comment by esavignone** [comment]
Olá @ghayashi ,

Podemos fechar este bug?

Obrigado,

**Comment by esavignone** [comment]
Oi @ghayashi ,

O ticket será fechado, por favor reabrir se o problema persistir.

Obrigado,
