### ISSUE TITLE
Erro em pagamento completo com um cartão em uma compra com dois cartões

### ISSUE THREAD

**Issue by rafaelcunha** [mercadopago/cart-magento#124]
Bom dia todos!
Tem um usuário do módulo, Lenharo Mega Store, em que está acontecendo o seguinte problema:

Segundo informações do administrador do site, um cliente fez uma compra com um cartão. Então ele cancelou o pagamento com esse cartão, mas fez o pagamento total com outro cartão.

No sistema do mercadopago (API MerchantOrders), essa compra aparece como sendo uma compra realizada com dois cartões e o status atual para um dos cartões é cancelado e para o outro aprovado (com o pagamento do valor total do pedido).
Pelo magento, a informação do pedido que o cliente me mandou é:

Número do cartão: xxxx xxxx xxxx 8346 | xxxx xxxx xxxx 3714
Método de Pagamento: visa | visa
Parcelas: 7 | 3
Identificação na Fatura: MERCADOPAGO*
Mensagem da Operadora : approved | cancelled
Payment Detail: accredited | expired

O problema é que apesar do cliente ter pago a compra completamente, o sistema ainda não gerou o pedido.
Há alguma verificação de que o valor pago pelos cartões batem ou não o valor total da compra?
Acredito que nesse caso, o que pode estar acontecendo, é que para gerar o pedido está sendo aguardado que o status dos cartões todos seja aprovados. Porém acredito que antes, deveria ser verificado se o valor pago pelos cartões é o mesmo da compra. Isso faria com que nesse caso, a fatura fosse gerada, mesmo um dos cartões sendo cancelado, pois o valor pago bateria com o valor do pedido.

Até!
Rafael de Aquino Cunha

**Comment by fcapua-summa** [comment]
Olá @rafaelcunha,

Obrigado por entrar em contato conosco, iremos rever este caso e atualização em breve.

**Comment by imasson** [comment]
olá @rafaelcunha . 
Ele tem sido capaz de resolver o problema com a nova versão do módulo?
Lembranças!

Ivan Masson.
