### ISSUE TITLE
Notification_url https

### ISSUE THREAD

**Issue by rafaelcunha** [mercadopago/cart-magento#125]
Bom dia todos!
   O usuário Lenharo Mega Store me relatou que quando acontece um pedido, seus status não estavam sendo atualizados sempre, apenas em alguns casos.
   Ao analisar o problema, percebi que quando um pedido era aprovado rapidamente, no momento em que se colocava o pagamento, seu status era aprovado corretamente e os processos decorrente disso aconteciam normalmente. Porém, quando um pagamento entrava em análise ele permanecia nesse estado indefinidamente.
   Pela API de pagamentos do mercadopago, verifiquei que o pagamento já havia sido aprovado, porém seu status não era atualizado no magento. E ainda verifiquei que o servidor de IPN continha o status http 500 para a tentativa de notificação.
   Ao fazer o post manualmente na notification url enviada no pagamento, POST http://www.lenharomegastore.com.br/mercadopago/notifications/custom?type=payment&data.id=ID_PAGAMENTO, obtinha o erro http 404.
   Finalmente, descobrimos que a notification url deveria ser https e não http, sendo o POST na url: https://www.lenharomegastore.com.br/mercadopago/notifications/custom?type=payment&data.id=ID_PAGAMENTO, funcionou corretamente.

   Alteramos o código diretamente para enviar a notification url com https, porém acredito que o melhor seria que o usuário indicasse na configuração do módulo se seu endereço de notificação é http ou https, deixando o http como padrão.

Até mais!
Rafael de Aquino Cunha

**Comment by fcapua-summa** [comment]
Olá @rafaelcunha,

Obrigado por entrar em contato conosco, iremos rever este caso e atualização em breve.

**Comment by kinfoxxx** [comment]
Olá, @rafaelcunha estou tendo esse mesmo problema, por favor qual arquivo que você alterou ?
