### ISSUE TITLE
se puede habilitar el pago con plata en cuenta? solo veo tarjetas de credito y rapipago etc

### ISSUE THREAD

**Issue by delfidream** [mercadopago/cart-magento#126]

**Comment by fcapua-summa** [comment]
Hola @delfidream, esa opción solo se encuentra disponible en el checkout standard. Luego de loggearse y si tiene plata disponible en la cuenta.

Saludos!

**Comment by delfidream** [comment]
cual es el checkout standard? Lo puedo habilitar? No entiendo bien a que te
referis.



*Delfina Rossi *

2016-04-18 17:55 GMT-03:00 Facundo Capua <notifications@github.com>:

**Comment by fcapua-summa** [comment]
Hola @delfidream,
Tal como dice la documentación hay 2 tipos de checkout en la integración con Mercado Pago: https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x#configuration

Podes encontrar las configuraciones de este checkout en:
**System > Configuration > Sales > Payment Methods > Mercado Pago - Classic Checkout**

Saludos!

**Comment by delfidream** [comment]
Hola Facu, eso lo veo, pero en ningun momento me pide credenciales de mi
usuario de  mercadopago, solo usa las de magento, con lo cual es imposible
que detecte mi plata en cuenta. Puedo setearlo para que me pida las
credenciales de mercadopago asi me aparece esa opcion?



*Delfina Rossi *
