### ISSUE TITLE
Error en server luego de actualizar version

### ISSUE THREAD

**Issue by arnoldmontiel** [mercadopago/cart-magento#129]
Luego de actualizar a d5ff049 me encontré con el siguiente error al intentar entrar a  las configuraciones

[Thu Apr 21 16:30:30.881641 2016] [:error] [pid 2667] [client 190.220.162.208:39163] PHP Fatal error:  Call to a member function getAllItems() on a non-object in /var/www/sites/quedapintada/app/code/community/MercadoPago/MercadoEnvios/Model/Shipping/Carrier/MercadoEnvios.php on line 88, referer:

en este archivo en la linea 88 econtré:

$dimensions = $helperMe->getDimensions($helperMe->getAllItems($this->_request->getAllItems()));

donde $this->_request es NULL

¿Que debería hacer? Seguí todos sus pasos para el upgrade

**Comment by fcapua-summa** [comment]
Hola @arnoldmontiel,
Hemos recibido varios casos similares a este, y si bien nosotros no hemos podido reproducirlo en nuestros entornos hemos hecho algunos ajustes que deberían evitar este error.

Te pido que te actualices a la última versión que acabamos de publicar y nos digas si te sigue ocurriendo: https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x

Muchas gracias!

**Comment by arnoldmontiel** [comment]
Muchas gracias, esta nueva versión solucionó el problema que tenia.
