### ISSUE TITLE
Opcion de mercado envios no aparece en checkout

### ISSUE THREAD

**Issue by delfidream** [mercadopago/cart-magento#131]
Estimados, tengo instalado el plugin, con el ultimo update. Tengo una cuenta de mercadopago de tipo vendedor con mercadoenvios activado. Tengo el sistema configurado asi:

![menvios01](https://cloud.githubusercontent.com/assets/8285596/14754178/0946ed18-08b0-11e6-99cf-0731635b6a79.jpg)
![menvios02](https://cloud.githubusercontent.com/assets/8285596/14754180/12c3d892-08b0-11e6-8b5a-3faa555fea15.jpg)

Pero en el checkout ni siquiera me aparece la opcion de mercadoenvios.

La parte de mercado pago anda barbaro, que me falta para que funcione mercadoenvios?

**Comment by dachaga** [comment]
Hola, para que MercadoEnvìos aparezca, debe poder calcularse el costo de envío. para esto, todos los items del carrito deben tener seteados sus respectivos valores de alto, largo, ancho y peso, además la suma de las dimensiones no debe superar las establecidas por OCA. 
Si en cualquier caso querés que aparezca con un mensaje de que no pudo calcularse el costo, podes configurar las opciones "Show method if not applicable" y "Mensaje de error mostrado".

**Comment by delfidream** [comment]
Era eso. Gracias!!!!!!
