### ISSUE TITLE
Asignacion automatica de numeros de seguimiento

### ISSUE THREAD

**Issue by delfidream** [mercadopago/cart-magento#132]
Estimados,
tengo el plugin funcionando en modo sandbox.
Hago un pedido, me aparecen los costos de envio, proceso la orden, etc.
Tengo dos consulta 
1) no estoy viendo numeros de seguimiento, deberia asignarlos yo a mano? Se deberian poner automaticamente?
2) no me anda la generacion de etiquetas, abre por un segundo una pagina vacia y recarga la misma pagina de envio en la que estaba. Puede ser por la falta de numero de seguimiento o que puede ser?

Saludos.

**Comment by delfidream** [comment]
el boton de print shipping label si lo inspecciono sale vacio :
window.open(' ')

**Comment by dachaga** [comment]
Hola, por el momento, MercadoEnvìos no está funcionando con el  modo sandbox de Mercado Pago.
Te recomiendo que deshabilites el modo sandbox y utilices las tarjetas de crédito de test https://www.mercadopago.com.ar/developers/es/solutions/payments/basic-checkout/test/test-payments/) para realizar tus pruebas de  MercadoEnvíos.

**Comment by delfidream** [comment]
Cuando intento usar las tarjetas de test me dice esto:

Mastercard no procesó el pago
Usar otra tarjeta u otro medio de pago.

Y un boton de "Usar otro medio de pago" . 

Me pasa lo mismo con Visa y Amex

**Comment by delfidream** [comment]
perdon, no lei que tenia que crear los usuarios y demas... cierro el issue hasta poder probarlo correctamente.
