### ISSUE TITLE
Cannot repeat Magento Product size attributes

### ISSUE THREAD

**Issue by marceloddr** [mercadopago/cart-magento#133]
Estou com esse erro ao tentar colocar em funcionamento o mercadoenvios, após adicionar o módulo a loja, não consigo fazer nenhuma alteração na parte de entregas. Versão do Magento 1.9

**Comment by dachaga** [comment]
Olá, este é porque a configuração dos atributos das dimensões , coloque atributos repetidos . Você deve escolher um atributo diferente para cada dimensão (altura, comprimento, largura e peso).

![configs](https://cloud.githubusercontent.com/assets/6785774/14921554/2be06472-0e09-11e6-9ab4-d026018ef805.png)

**Comment by marceloddr** [comment]
Deu certo. Obrigado
