### ISSUE TITLE
Erro ao finalizar pedido

### ISSUE THREAD

**Issue by richard-nexxus** [mercadopago/cart-magento#135]
Boa tarde

Instalei o modulo e quando vou finalizar o pedido no cartão ele me dá a mensagem** "Não foi possível processar seu pagamento , neste momento . Por favor verifique os dados do formulário e tente novamente mais tarde"**.

O que poderia ser?

**Comment by dachaga** [comment]
Olá, você pode habilitar os logs MercadoPago e enviar as informações?
Por outro lado, certifique-se que se você estiver usando one page checkout, a configuração ativa onestepcheckout não está ativado.
Saudações!
![configs](https://cloud.githubusercontent.com/assets/6785774/15359006/9c71903e-1cdd-11e6-87d8-961e88cbc982.png)

**Comment by richard-nexxus** [comment]
Ativei os certificado SSL e funcionou, obrigado
