### ISSUE TITLE
Erro ao Inserir Modulo

### ISSUE THREAD

**Issue by vfernandes1988** [mercadopago/cart-magento#136]
Recebo o erro de:
SSL certificate problem: unable to get local issuer certificate

Ja criei um certificado e coloquei no php porem nao resolveu.

**Comment by fcapua-summa** [comment]
Oi @ vfernandes1988,
- Onde você está recebendo este erro?
- Qual versão do PHP você tem?
- Qual versão do Magento tem?
- Qual é a versão do plug-in MercadoPago obtida?

**Comment by esavignone** [comment]
Olá @vfernandes1988 ,

Podemos fechar este ticket?

Obrigado,

**Comment by esavignone** [comment]
Oi @vfernandes1988 ,

O ticket será fechado, por favor reabrir se o problema persistir.

Obrigado,
