### ISSUE TITLE
MercadoEnvío no utiliza los datos del cliente de Magento

### ISSUE THREAD

**Issue by echi22** [mercadopago/cart-magento#137]
Hola. quería saber si es un error de configuración mio o si es un problema del plugin, pero en el proceso de compra, Magento solicita al cliente que ingrese los datos del envio. Sin embargo al confirmar la compra y pasar al frame de mercadopago, se vuelve a solicitar que el cliente escriba sus datos personales y su dirección de envío.

Existe alguna forma de evitar la doble carga de los datos??

**Comment by fcapua-summa** [comment]
Hola @echi22 por ahora esta es la forma en que trabaja la integración, no es ningún error de configuración.
Estamos trabajando para ver de simplificar el proceso para el usuario final.

Saludos!
