### ISSUE TITLE
bool(false) error

### ISSUE THREAD

**Issue by nshields08** [mercadopago/cart-magento#14]
Hola,

Magento me sigue mostrando un error cuando trato de instalar este extension.

Aquí está una imagen del error que me muestra:
https://www.dropbox.com/s/ch5d4ofaor7qch9/bool%20%28false%29%20mercado%20pago%20extension%20error%20magento.jpg

Por favor, ayúdeme a resolver esto. ¡Gracias!
![bool false mercado pago extension error magento](https://f.cloud.github.com/assets/3371851/94234/e3d4d27c-6644-11e2-85fe-92281ac77a18.jpg)

**Comment by viniciuscenci** [comment]
Estou tendo o mesmo problema no magento 1.9.
PHP 5.3.28, CURL enabled...

Alguma solução ou algo do php que o módulo utilize e que posso verificar?

**Comment by esavignone** [comment]
Oi @viniciuscenci ,

O ticket será fechado, por favor reabrir se o problema persistir.

Obrigado,
