### ISSUE TITLE
Campos não aparecem após atualizar para MercadoPago (0.0.4)

### ISSUE THREAD

**Issue by smarley2** [mercadopago/cart-magento#140]
Olá pessoal, atualizei o módulo do MercadoPago para a versão 0.0.4 e agora estou com um problema.

Os campos de mês, ano e parcelas não aparecem para os clientes.
Após clicar nos mesmos ele continua em branco.

Utilizo o módulo OSC do Pagarme feito pela Inovati.

Alguém tem um dica para resolver este problema?

Obrigado!

![mercadopago](https://cloud.githubusercontent.com/assets/7862619/15411819/1132ab44-1df9-11e6-9421-20a419fddb62.JPG)

**Comment by dachaga** [comment]
Olá, eu recomendo que você atualizar o plugin para a versão mais recente (2.1.2).

https://github.com/mercadopago/cart-magento/tree/2.1.2

E para ativar o uso de OSC.
![configs2](https://cloud.githubusercontent.com/assets/6785774/15426657/291c3474-1e66-11e6-8fe6-5f51876de7a2.png)

**Comment by smarley2** [comment]
Estava ativo.

Acabamos por optar pelo outro método onde há redirecionamento para a página do MercadoPago.
De qualquer forma agradeço, no futuro atualizaremos.
