### ISSUE TITLE
 Por favor verifique os dados do formulário e tente novamente mais tarde

### ISSUE THREAD

**Issue by richard-nexxus** [mercadopago/cart-magento#141]
Alguns dias atrás abri uma issue com o erro de **Não foi possível processar seu pagamento , neste momento . Por favor verifique os dados do formulário e tente novamente mais tarde**, ativei o certificado SSL e funcionou, porem está me dando a mensagem novamente, o que pode ser? No admin está correto de acordo com meu checkout e configs e nos logs não constam nada. e Se ativo o modo Debug ele da a mensagem **payment_method_id attribute can't be null**

**Comment by esavignone** [comment]
Olá @richard-nexxus ,

Onde você está recebendo este erro?
Qual versão do PHP você tem?
Qual versão do Magento tem?
Qual é a versão do plug-in MercadoPago obtida?

Obrigado,

**Comment by richard-nexxus** [comment]
Recebo o erro na hora de finalizar o pedido com boleto.
Versão do PHP: 5.5
Versão do Magento: 1.9.2.2
Versão do plug-in: 1.6.x-1.9.x ( Ultima atualização)

**Comment by esavignone** [comment]
Oi @richard-nexxus, 

Podes enviar a informação de ambiente a esavignone@summasolutions.net para ajudar melhor com o bug?

Obrigado,

**Comment by richard-nexxus** [comment]
Claro, já enviei

**Comment by esavignone** [comment]
Oi @richard-nexxus ,

O ticket será fechado, por favor reabrir se o problema persistir.

Obrigado,
