### ISSUE TITLE
Pagamento não muda de status

### ISSUE THREAD

**Issue by rafaelobo** [mercadopago/cart-magento#142]
Atualizamos para a última versão do plugin e o pagamento simplesmente vai para um status que não está nem na listagem de configuração do plugin no magento: **Pagamento Pendente** , e não há qualquer notificação ou mudança de status. Enquanto que o módulo anterior funciona ok nessa parte, porém está bugado em outras. Como resolvemos isso ?

**Comment by imasson** [comment]
Olá @rafaelobo 
O status do pedido está pendente até que o pagamento é recebido a notificação IPN.
Certifique-se de que você tem disponível o seu Domio para alcançar estes notificaicones.
Saudações.

**Comment by esavignone** [comment]
Oi @rafaelobo ,

O ticket será fechado, por favor reabrir se o problema persistir.

Obrigado,
