### ISSUE TITLE
Diferentes metodos de pago que ofrece mp 

### ISSUE THREAD

**Issue by Scatagua** [mercadopago/cart-magento#144]
Hola queria saber si este pluging solo tiene disponible el metodo de pago tarjeta de credito?

Ya que tengo  un magento multisite y en cada website quiero configurar los metodos de pago  que trae mercadopago disponible por pais ejemplo para Colombia 

- Hasta en 36 cuotas con tarjeta
- En efectivo
- Transferencia bancaria
- Con saldo recargado en tu cuenta de MercadoPago

Pero no se si estan disponibles en este plugin solo veo disponible tarjeta de credito

**Comment by esavignone** [comment]
Hola @Scatagua,

El plugin cuenta con el método tarjeta de crédito y también con el Checkout Standard, donde podes acceder mediante iframe/pop-up directamente a Mercado Pago donde se ofrece el resto de los métodos de pago.

Podes encontrar más información en el siguiente link https://github.com/mercadopago/cart-magento

Saludos,

**Comment by esavignone** [comment]
Hola @Scatagua,

El ticket será cerrado, por favor reabrir si el problema persiste.

Muchas gracias!
