### ISSUE TITLE
Status do pagamento não altera com pedido aprovado no mesmo segundo.

### ISSUE THREAD

**Issue by kinfoxxx** [mercadopago/cart-magento#147]
Olá, estamos com o seguinte problema, quando temos um pagamento por cartão e o pagamento identifica no mesmo segundo o status não altera para aprovado, quando o pagamento demora um pouco a aprovar o status altera normalmente.

**Comment by gmatsuoka** [comment]
Olá @kinfoxxx , tudo bem?

Você pode enviar os logs de erros que estão na pasta "raiz_do_magento/var/log" e também se possível informar alguns numeros de pedidos que isso ocorreu?

Atenciosamente,

Gabriel

**Comment by gmatsuoka** [comment]
Olá @kinfoxxx,

O erro persiste?

Atenciosamente,

Gabriel.

**Comment by kinfoxxx** [comment]
Boa tarde @gmatsuoka , persiste sim, não tivemos tempo de pegar o log, fazendo a identificação de forma manual a cada venda pelo mercado pago entrando no link link http://www.kshopsa.com.br/mercadopago/notifications/custom?type=payment&data.id=ID_PAGAMENTO , assim o status altera .

**Comment by smarley2** [comment]
Olá @kinfoxxx @gmatsuoka estou com o mesmo problema na minha loja.
Alguma solução até o momento?

Tentei utilizar esta atualização manual que o @kinfoxxx postou mas não parece ter funcionado, em ID_PAGAMENTO coloquei a número de pagamento recebido do mercadopago.

Obrigado.

**Comment by kinfoxxx** [comment]
Boa noite, nada de solução ainda, de cada 10 vendas 9 não se altera o status .

**Comment by smarley2** [comment]
Na realidade as minhas ultimamente nenhuma altera sozinha.
Estou com a versão 1.9.3 porém aconteceu na 1.9.2.1 também.

Realmente se eu vendesse 50 por dia seria bem chato, por enquanto consigo fazer manual.
Mas que é ruim é...
