### ISSUE TITLE
[ERRO] Não foi possível processar seu pagamento, neste momento...

### ISSUE THREAD

**Issue by guztavoalves** [mercadopago/cart-magento#148]
Olá, 
instalei o módulo no Magento 1.9.2.4, cadastrei as credenciais de acesso e habilitei o "Custom Checkout", porem quando tento fazer uma compra por meio dessas formas de pagamento e seleciono "Mercado Pago", não exibe os campos para preenchimento do Cartão de Crédito e nem finaliza a compra, também quando tento pagar por boleto, volta uma mensagem:

"Não foi possível processar seu pagamento, neste momento. Por Favor verifique os dados do formulário e tente novamente mais tarde."

Alguém sabe o que pode ser esse erro?

**Comment by gmatsuoka** [comment]
Olá @guztavoalves, tudo bem?

Você pode enviar um ambiente para que eu possa fazer os testes? também se possível enviar os logs de erros que se encontra na pasta "raiz_do_magento/var/log" os arquivos possuem o nome començando com mercadopago.

Atenciosamente,

Gabriel.

**Comment by guztavoalves** [comment]
Olá @gmatsuoka,

por favor envie um email para guztavoalves@hotmail.com com seus contatos, para que possamos combinar um horário para você analisar o módulo instalado em uma das lojas que possuo.

Eu precisei voltar o módulo para uma versão antiga, que não apresenta esse bug.

Abs

**Comment by gmatsuoka** [comment]
Olá @guztavoalves,

Email enviado.

Atenciosamente,

**Comment by guztavoalves** [comment]
Olá @gmatsuoka ,
respondi seu email com diversas informações sobre o BUG.

obrigado
