### ISSUE TITLE
Error installing MercadoPago

### ISSUE THREAD

**Issue by Cellin** [mercadopago/cart-magento#149]
Hello/Olá,

Estou com problema instalando MercadoPago, na hospedagem Kinghost. Versão do magento 1.9.2.4, PHP 5.4 e MySQL 5.5.43
I have a problem installing MercadoPago, on a Brazilian host. Magento version: 1.9.2.4, PHP 5.4, and MySQL 5.5.43.

Porém, ele não funciona quando acesso o sistema, tento limpar o cache, aparece este erro:
When i try to access system, or try cleaning cache, shows these errors:

Parse error: syntax error, unexpected '[' in app/code/community/MercadoPago/MercadoEnvios/Model/Shipping/Carrier/MercadoEnvios.php on line 56  -  Em/In sistema.

Parse error: syntax error, unexpected '[' in /app/code/community/MercadoPago/MercadoEnvios/Model/Observer.php on line 131
Em/In cache.. e etc..

**Resolvido!**

**Comment by esavignone** [comment]
Hi @Cellin , 

Do you still have the issue? It's not clear to me if it was resolved or not.

Thanks in advance!

**Comment by esavignone** [comment]
Hi @Cellin ,

Any word on this?

Best,

**Comment by jeffcarpentieri** [comment]
boa noite como vc conseguiu arrumar estou com mesmo problema obrigado

**Comment by imasson** [comment]
Hello @jeffcarpentieri this problem is related to current php version installed in your server.
