### ISSUE TITLE
Alterar mensagem de confirmação do pedido

### ISSUE THREAD

**Issue by magnored** [mercadopago/cart-magento#151]
Como faz para alterar esta mensagem:
![image](https://cloud.githubusercontent.com/assets/7586874/16119083/499df4ee-33b0-11e6-84be-2e074b9cb430.png)

Esse nome descritivo **REJECTED OTHER REASON** fica feia para ser para o cliente, gostaria pelo menos de traduzi-lo para português 

Obs: até o status de confirmação fica em ingles, no caso aparece **ACCEPTED**

**Comment by esavignone** [comment]
Oi @magnored ,

"cc_rejected_other_reason" é um código de estado de Mercado Pago , não um texto que pode ser traduzido.

Obrigado
