### ISSUE TITLE
Erro Js

### ISSUE THREAD

**Issue by az2009** [mercadopago/cart-magento#152]
Alguém já teve esse problema de js "Uncaught Invalid element" no árquivo /js/mercadopago/tinyJ.js:177: 
throw "Invalid element";

**Comment by esavignone** [comment]
Olá @az2009 ,

Qual é a versão do plug-in MercadoPago obtida?

Obrigado,

**Comment by mfthiago** [comment]
Estou com o mesmo problema... v1.6.x - 1.9.x

**Comment by esavignone** [comment]
Olá @mfthiago ,

Qual é sua versão do plug-in?

Obrigado,

**Comment by az2009** [comment]
v1.6.x - 1.9.x

**Comment by az2009** [comment]
Alguém conseguiu resolver?

**Comment by imasson** [comment]
Hi @az2009 @mfthiago  are you using a custom magento checkout? like OneStepChekout or similar?

**Comment by az2009** [comment]
Resolvi
