### ISSUE TITLE
Php versión 

### ISSUE THREAD

**Issue by ferxtr** [mercadopago/cart-magento#154]
La. Última versión que lanzaron me pide una versión de php anterior a la que tengo actualmente,  no puedo volver para atras con eso

**Comment by fcapua-summa** [comment]
Hola @ferxtr , ¿cómo estás instalando el plugin? ¿Qué versión de PHP tenes instalada?

**Comment by ferxtr** [comment]
Hola, tengo La 5.6, lo estaba haciendo desde magento connect, pense en
bajarme los archivos y ver que pasaba.
Igualmente en la version de mercadopago que tengo ahora que es la 0.0.3 no
logre habilitar mercadoenvios, me dice que no esta disponible

**Comment by imasson** [comment]
Hola @ferxtr como estas? 
Pudiste resolver el problema con la nueva version del plugin?
Saludos!
