### ISSUE TITLE
Error PHP version

### ISSUE THREAD

**Issue by juanpaThalu** [mercadopago/cart-magento#155]
I want to install on my server with PHP 5.5.9 and I returned the following error message:

> CONNECT ERROR: Package community/MercadoPagoTransparent 2.3.0: requires PHP version >= 5.4.0 and <= 5.5.0 current is: 5.5.9-1ubuntu3.11

But in the release documentation requirements contained within:

> **# Requirements:**
> 
> Operating System
> 
> Linux x86-64
> Web Server
> 
> Apache 2.x
> Nginx 1.7.x
> Database
> 
> MySQL 5.6 (Oracle or Percona)
> PHP
> 
> PHP 5.4.x
> **# PHP 5.5.x**

They could help me solve this problem?

**Comment by fcapua-summa** [comment]
Hi @juanpaThalu 

We are reviewing this problem, in the meanwhile you can download the latest version from here and install it manually:
https://github.com/mercadopago/cart-magento/releases/tag/2.3.0

Thanks!

**Comment by smarley2** [comment]
Olá @fcapua-summa 

Existe alguma previsão para a solução?

Minha versão ainda é a 0.0.4 está funcionando bem porém gostaria de atualizá-la.
Vi sua recomendação para atualização manual porém me sinto mais confortável atualizando através do connect.

Obrigado!

Também estou com o erro abaixo:
CONNECT ERROR: Package community/MercadoPagoTransparent 2.3.1: requires PHP version >= 5.4.0 and <= 5.5.37 current is: 5.6.24

**Comment by imasson** [comment]
Hi @smarley2 magento connect doesn't allow to install extensions with php PHP 5.5.9. 
One solution is to manually copy module files as fcapua suggested.
Regards,
Ivan Masson
