### ISSUE TITLE
Error con shipping_cost en modo sandbox

### ISSUE THREAD

**Issue by JorgeEMX** [mercadopago/cart-magento#156]
Hola buen día,

Estamos intentando agregar mercado pago a un sitio y estamos realizando pruebas en Sandbox con Magento EE 1.13. Se intenta terminar el proceso de compra en el checkout de mercado pago con URL mercadopago/pay/, una de las llamadas que se invoca cuando se da "Confirmar pago" marca el siguiente error:

URL: 
checkout/ajax/postPayment
Response: 
`{"action":"error","error":{"message":"The name of the following parameters is wrong : [shipping_cost]","error":"bad_request","status":"400","cause":"null"},"code":"8","payment_id":null,"status":400}`

Es algún problema con el ambiente Sandbox? o es problema de los parametros que recibe una vez que se crea el pedido y se redirecciona al checkout de mercado pago?

La versión de mercado pago es la última estable 2.3.0. También comentar que de ahí nunca pasa al success page del sitio y los pedidos siempre quedan como pendiente.

![screenshot from 2016-06-24 11-08-23](https://cloud.githubusercontent.com/assets/6845831/16344244/3a624b5e-3a01-11e6-86fd-4c711ec13ac2.png)

Saludos

**Comment by gmatsuoka** [comment]
Hola @JorgeEMX,

Estas haciendo las pruebas en cuál país? estas utilizando usuário de test?

Saludos!

**Comment by andresmartindoria** [comment]
Hola @JorgeEMX , @gmatsuoka , como están?

Estoy con el mismo problema. Estoy desarrollando para Argentina. @JorgeEMX , pudiste solucionarlo? si es así, como ?

Muchas gracias!

**Comment by gmatsuoka** [comment]
Hola @JorgeEMX y @andresmartindoria , todo bien?

Mi consejo es utilizar los usuarios de prueba (test) en un entorno de producción.

El entorno de sandbox es un poco inestable.

Slds,

**Comment by leamasuero** [comment]
Hola @JorgeEMX . ¿Pudiste solucionar el problema? Me sucede lo mismo...

**Comment by andresmartindoria** [comment]
Hola @leamasuero , el checkout básico no tiene modo sanndbox, entonces tenes que instalar un certificado en tu local, para hacer pruebas, o bien hacer el checkout personalizado.

Igual es increíble que no tenga un modo sandbox... flojo ML.

Saludos!
