### ISSUE TITLE
(Erro) Não foi possível processar seu pagamento , neste momento . Por favor verifique os dados do formulário e tente novamente mais tarde

### ISSUE THREAD

**Issue by coemoraes** [mercadopago/cart-magento#157]
Ola, Boa tarde!

Estamos recebendo essa mensagem quando tentamos finalizar utilizando cartão de crédito.

Estamos utilizando uma versão do OSC 4.0.Pro.

[message:protected] => Não foi possível processar seu pagamento , neste momento . Por favor verifique os dados do formulário e tente novamente mais tarde
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /var/www/app/code/community/MercadoPago/Core/Model/Custom/Payment.php
    [line:protected] => 87

Pode acessar o ambiente de testes.

dev.k2everest.com.br

Caso queira acesso a backend, favor nos informar também, temos repositorio no Bitbucket caso tenha interesse.

Obrigado.

Coe Moraes

www.k2everest.com.br

11 96366 8044

**Comment by gmatsuoka** [comment]
Olá Coe, tudo bem?

Você pode enviar o log do Mercado Pago que esta na pasta "var/log".

Atenciosamente,

**Comment by coemoraes** [comment]
Nos , trocamos o OSC para a versao mais moderna , e aparentemente resolveu na dev, usando https de teste, na producao , estamos sem https ainda., portanto não temos como testar, vou providenciar o log da dev.
