### ISSUE TITLE
Magento 2

### ISSUE THREAD

**Issue by lucasgonzalez** [mercadopago/cart-magento#158]
Hola,

Esta pensada la migración para poder usarse en Magento 2?

Muchas gracias.

**Comment by imasson** [comment]
Hola @lucasgonzalez !
Te paso el repositorio donde se encuentra el desarrollo del modulo para magento 2,
[https://github.com/SummaSolutions/cart-magento2](https://github.com/SummaSolutions/cart-magento2)

Esta en etapa de desarrollo pero completamente funcional.
Saludos,
Ivan.
