### ISSUE TITLE
Magento 2.0 Modelo

### ISSUE THREAD

**Issue by jota-xx** [mercadopago/cart-magento#159]
Estoy integrando un site con magento 2.0, pero necesito el modulo de mercado pago. Pero no esta para la version 2.0 de magento. Esta en desarrollo? donde puedo obtener informacion?

Muchas gracias

**Comment by imasson** [comment]
Hola @jota-xx  !
Te paso el repositorio donde se encuentra la version del modulo para Magento 2,
https://github.com/SummaSolutions/cart-magento2

Esta en etapa de desarrollo pero completamente funcional.
Saludos,
Ivan.

**Comment by jota-xx** [comment]
Muchas gracias, lo estare probando.
Saludos,

**Comment by jota-xx** [comment]
@imasson cual es la manera correcta de instalar el modulo de magento 2, de mercado pago?

**Comment by imasson** [comment]
Para instalar el modulo en Magento2, ademas de copiar los archivos del modulo en app/code, se debe activar por medio de la consola.
Esto es, ejecutando el siguiente comando en el directorio donde este instalado magento:

 bin/magento module:enable MercadoPago_Core

Y despues se actualiza magento con el nuevo modulo ejecutando:

 bin/magento setup:upgrade 

Gracias y quedamos a la espera de novedades,
Saludos

**Comment by jota-xx** [comment]
Perfecto! gracias.

**Comment by jota-xx** [comment]
@imasson disculpa que te consulte de nuevo, hice estos pasos y no veo el modulo dentro de stores/sales/Payment Methods , imagino que deberia aparecer una opcion ahi, veo los modulos por defecto (paypal, etc), pero no veo nada relacionado a Mercado Pago.
OTra cosa que veo raro, es que el modulo, o sea dentro app/code/MercadoPago/ no veo "codigo" veo la definicion del modulo, pero no veo archivos (block, etc, i18n, etc) las carpetas bases de los modulos. 
Muchas Gracias,  increiblemente conoces o laburas en el mismo lugar donde trabaja Aime, q casualidad.

**Comment by imasson** [comment]
Hola @jota-xx si ayer me conto aime que casualidad!

Seguramente te has bajado el branch master, el codigo esta en develop, seria aca
[https://github.com/SummaSolutions/cart-magento2/tree/develop](https://github.com/SummaSolutions/cart-magento2/tree/develop)

Saludos!

**Comment by jota-xx** [comment]
Si tenia otros archivos, pruebo esto.
Gracias!

**Comment by jota-xx** [comment]
De nuevo consultando. Ahi lo instale, y parece q todo quedo ok, pero ahora voy a stores/sales/Payment Methods y no me muestra nada, o sea dejo demostrar las demas formas de pago.
Tenes idea? Perdon las molestias.
Gracias

**Comment by imasson** [comment]
Se econtro un problema con los certificados SSL usando windows.

Para resolverlo descargar el archivo https://curl.haxx.se/ca/cacert.pem
Y modificar la linea ";curl.cainfo = " del archivo php.ini indicando la ubicacion de cacert.pem
Luego reiniciar PHP

Saludos.

**Comment by sergiojump** [comment]
Buenas tardes, estoy instalando la extension de Mercado Pago en Magento 2, copio los archivos sueltos incluyendo la carpeta scr dentro de app/code, pero despues cuando voy a la consola , me dice Unknown module(s): 'MercadoPago_Core' para ambos modulos, por favor podrian ayudarme?
Muchas gracias y saludos !!!!
