### ISSUE TITLE
Error PHP y MercadoEnvios no funciona

### ISSUE THREAD

**Issue by martinmatus100** [mercadopago/cart-magento#161]
Hola,
Tengo un inconveniente con MercadoEnvios en la seccion Metodos de Envio del checkout. 
Instale las versiones 2.3.1 y 2.3.0 manualmente y mercadoenvios no funciona:
"Lamentamos informarle que en este momento no hay cotizaciones disponibles para este pedido."
También intente desde magento connect y me dice que solo funciona para PHP 5.4 a 5.5, yo tengo PHP 5.6.

**Comment by gmatsuoka** [comment]
Hola @martinmatus100 , todo bien?

Devuelve este mensaje cuando los atributos del producto excede el valor máximo.

Puedes enviar los registros de errores para analizarmos mejor?

Slds,
