### ISSUE TITLE
Error en Seleccionar Método de pago

### ISSUE THREAD

**Issue by lore77** [mercadopago/cart-magento#163]
Buenas noches tras instalar los archivos para mercado pago, y al acceder a a la configuraci´n de Magento - Métodos de pago, me da el siguiente error:

app/code/community/MercadoPago/Core/Model/Source/Country.php on line 22

Gracias 

Saludos

**Comment by imasson** [comment]
Hola buen dia @lore77 pudiste solucionar el error?
Saludos!
