### ISSUE TITLE
Estato de pedido incorrecto

### ISSUE THREAD

**Issue by arnoldmontiel** [mercadopago/cart-magento#164]
Queria consutlar por el estado en el que queda un pedido cuando el cliente hace click en "«Cancelar y volver a MI SITIO". 
El sismtema vuelve a magento (se cierra el iframe) con la leyenda: "Se produjo un error durante el artículo de pago"

En este caso el estado queda en estado "Pending" y sin ningun historial de lo que ha sucedido, existe la opción de manejar este evento? Hay una lista de estados que se pueden configurar en las opciones, pero ninguna para este caso de uso, muchas gracias

**Comment by gmatsuoka** [comment]
Hola @arnoldmontiel , todo bien?

El módulo sólo registra un histórico cuando hay un pago, en este caso no se ha completado el pago.

Slds,
