### ISSUE TITLE
"Tivemos um problema, tente novamente" na página do MP

### ISSUE THREAD

**Issue by andrekutianski** [mercadopago/cart-magento#165]
Estou realizando testes no modo sandbox do mercadopago para processamento dos pegamentos de uma loja magento mas estou enfretando problema nos testes **DENTRO** da url do mercadopago. 

Nenhum pedido é processado, só é informado **"Tivemos um problema, tente novamente"** em qualquer meio de pagamento que seja tentato. Do lado da nossa loja os logs demonstram que tudo esta aparentemente se comunicando. Envio informações dos usuarios de teste usados e também tela da finalização do pedido.

realizei a configuração também através de usuários testes da conta MP como informado no link [Usuários Testes](https://www.mercadopago.com.br/developers/pt/solutions/payments/basic-checkout/test/test-users/)

já tentamos várias variações de informações e teste, mas o problema continua persistindo.

![sandbox-mercadopago](https://cloud.githubusercontent.com/assets/5316107/17501705/d8e0756a-5db7-11e6-855b-1ef0897c2c35.png)

**Comment by gmatsuoka** [comment]
Olá @andrebellafronte,

Tente testar no módulo produtivo (sem ser sandbox) com usuários de testes.

O ambiente de sandbox esta sofrendo por instabilidades e por esse motivo não esta processando os pagamentos de testes.

Abraço!

Gabriel.

**Comment by andrebellafronte** [comment]
valeu @gmatsuoka ! deu certo! Mas agora problemas no frete, o modulo consegue carregar o valor do frete mercado envios, atualiza os valores (estou usando o OSC-Magento-Brasil-6-Pro) e ao finalizar a compra, mensagem:

> Ocorreu um erro. Por favor, atualize a pagina.
{"status":400,"response":{"message":"Invalid dimension values.","error":"invalid_shipments","status":400,"cause":[]}}


nos logs do módulo, mesmo problema reportado:

> 2016-08-26T02:29:59+00:00 ERR (3): Request params:  - {"dimensions":"8x8x8,1000","zip_code":""}
2016-08-26T02:29:59+00:00 ERR (3): Error response API:  - {"status":400,"response":{"message":"Must provide destination","cause":null,"error":"must_provide_destination","status":400}}
2016-08-26T02:30:31+00:00 INFO (6): REQUEST SHIPMENT ME:  - {"mode":"me2","zip_code":"80010150","default_shipping_method":100009,"dimensions":"8x8x8,1000","cost":9.9}

**Comment by marlontseng** [comment]
Olá pessoal, somos uma publisher de jogos e vendemos nosso itens pelo mercadoshops. Do nada deu erro pros outros usuarios fazer compra aparece essa mensagens abaixo conforme a foto:

http://imgur.com/a/qmXIJ
http://imgur.com/a/PxDW9

Não sabemos o motivo já que não mexemos no API do pagamento..

Obrigado pela atenção.

**Comment by gmatsuoka** [comment]
Olá @andrebellafronte , tudo bem?

Você configurou o Mercado Envios na sua conta Mercado Pago?

Como esta as configurações no Magento, pode enviar um print-screen? 

Atenciosamente,

Gabriel.

**Comment by marlontseng** [comment]
Novamente além de entrar em contato com o suporte oferecido pelo mercado
livre e contato feito diretamente com vcs não tivemos solução até agora.
Faturamos mais de 60 mil por mês pela mercadoshops fora o meio de pagamento
do mercadopago que disponibilizamos dentro do jogo para nossos jogadores o
qual temos acesso de 100 mil jogadores por dia.

Agora nossas duas contas que criamos se encontram com mesmo problema,
bloqueado o meio de pagamento o qual o usuario final não consegue fazer
check out e até agora depois de uma semana não temos um respaldo. Queremos
saber com quem tratamos isso diretamente? Pq mais um dia assim vamos
cancelar nossa parceria e começar trabalhar com Payu e outros plataformas
que nos dão atenção devido.

O problema esta é bem simples. Acredito é só ver com pessoal responsavel e
destravar a conta.

Conta 1 que criamos foi pelo email vendas@xcloudgame.com
Loja: http://xtremegamex.mercadoshops.com.br/  (tivemos que trocar de nome
pq estava com problemas de check pros clientes.)


Conta 2
xgamecontato@gmail.com
Loja: http://bloodstrike.mercadoshops.com.br/ (criamos com nome da primeira
loja e mesmo endereço pq todos nossos clientes já estavam acostumados com
esse endereço)

PS notar que ambos mercadopago dentro do jogo e mercadolivre dessas duas
contas encontram o mesmo problema. Vcs mesmo podem fazer o teste do check
vai encontrar o problema. Não é possível que não haja solução disso.

Aguardo urgentemente uma resposta e prazo para resolvemos isso é até quarta
feira.

PS: A conta 2 foi resolvido. esta liberado para vendas, mas conta um
continua com problema. façam o teste desse produto e tenta fazer o check
out ele não aparece opções de pagamento.

http://produto.mercadolivre.com.br/MLB-765253160-camiseta-oficial-do-bloodstrike-frete-gratis-xcloudgame-_JM

Obrigado pela atenção e aguardo um retorno de vcs.

Abraço


Name : Marlon.T
Title : Marketing Manager
E-mail :marlon@xcloudgame.com <liudi@xcloudgame.com>
Skype : marlon_tseng
Website: www.xcloudgame.com

<https://cn.linkedin.com/pub/marlon-tseng/22/444/a03>

Address : Beijing Cultural Innovation Park, Chegongzhuang Avenue 4#,
Xicheng District, 100044

Em 21 de setembro de 2016 22:12, Gabriel <notifications@github.com>
escreveu:

**Comment by carhsant** [comment]
@andrekutianski Tenho os mesmos problemas, o site do MP é muito pobre em informações.

Conseguiu resolver, amigo?

**Comment by carhsant** [comment]
Como criou os usuários de teste?

**Comment by carhsant** [comment]
@andrekutianski
{"status":400,"response":{"message":"Invalid dimension values.","error":"invalid_shipments","status":400,"cause":[]}}

Este erro eu resolvi, era o peso e depois o valor, que não pode ser abaixo de 5.

**Comment by HenriqueMac** [comment]
Perderam um cliente muito importante que cresce cada dia mais.
por falta de suporte,.
XcloudGame

**Comment by marlontseng** [comment]
ola qual foi o erro do pagamento?

abraços


Name : Marlon.T
Title : Brazil Country Manager
E-mail :marlon@xcloudgame.com <liudi@xcloudgame.com>
Skype : marlon_tseng
Website: www.xcloudgame.com

<https://cn.linkedin.com/pub/marlon-tseng/22/444/a03>

Address : Beijing Cultural Innovation Park, Chegongzhuang Avenue 4#,
Xicheng District, 100044

2017-10-13 16:46 GMT-03:00 HenriqueMac <notifications@github.com>:

**Comment by marcellorg** [comment]
Galera como crio um usuário de teste?

**Comment by marlontseng** [comment]
como?


Name : Marlon.T
Title : Brazil Country Manager
E-mail :marlon@xcloudgame.com <liudi@xcloudgame.com>
Skype : marlon_tseng
Website: www.xcloudgame.com

<https://cn.linkedin.com/pub/marlon-tseng/22/444/a03>

Address : Beijing Cultural Innovation Park, Chegongzhuang Avenue 4#,
Xicheng District, 100044

2018-02-04 10:32 GMT-02:00 marcellorg <notifications@github.com>:
