### ISSUE TITLE
NAO PROCESSA PAGAMENTO ASSINATURA

### ISSUE THREAD

**Issue by peritoh1** [mercadopago/cart-magento#166]
QUEM PODE ME AJUDA O MEUS CLIENTES NAO TA CONSEGUINDO FAZER PAGAMENTO VIA MERCADO PAGO 
https://www.mercadopago.com/mlb/debits/new?preapproval_plan_id=c9586b8fa62e4a7b8f65aa2992115720

TODA VEZ QUE TENTA DA ERRO FALA QUE NAO BANCO NAO LIBEROU O PAGAMENTO MAIS DE 5 PESSOA TENTOU E NADA MESMO ERRO QUEM SABE OQUE PODE SER ?

**Comment by gmatsuoka** [comment]
Olá @peritoh1, tudo bem?

O módulo não tem integração com esse tipo de integração.

Qual módulo você esta usando?

Atenciosamente,

Gabriel.

**Comment by peritoh1** [comment]
to usando link normal mesmo envio pra os clientes ele nao consegue fazer o pagamento manda liga pra banco até com meu cartão tentei fazer nao foi.

**Comment by gmatsuoka** [comment]
Ola @peritoh1, tudo bem?

Isso significa que o pagamento do comprador não foi aprovado, por isso ele pede para ligar no banco para autorizar o pagamento.

No caso de duvidas não relacionadas ao Módulo Magento, por favor, envie no forum do developers do Mercado Pago: https://www.mercadopago.com.br/developers/pt/community

Atenciosamente,

Gabriel.
