### ISSUE TITLE
Pago efectivo - 500 internal_error

### ISSUE THREAD

**Issue by JavierSolis** [mercadopago/cart-magento#167]
Hola, estoy intentando realizar un pago en sandbox con pago efectivo, pero me responde

{
"status": 500
"response": {
"error": "mercadopago"
"message": "internal_error"
}-
}

He seguido ele ejemplo del chekput basico en php, consumido desde una app en android, realizando la esta llamada.

POST:
http://myserver.app/v1/pay/mp/doPayment

BODY:
 {
 "campaign_id":null,
 "card_issuer_id":null,
 "card_token":null,
 "installments":null,
 "item":
 {
 "id":"id1",
 "quantity":1,
 "unit_price":50
 },
 "merchant_access_token":"TEST-token",
 "payment_method_id":"pagoefectivo_atm"
 }

El sandbox esta fallando o es el request?

**Comment by gmatsuoka** [comment]
Hola @JavierSolis , todo bien?

Por favor, envíe la duda en el foros de Mercado Pago:
https://www.mercadopago.com.br/developers/es/community/

Slds,
