### ISSUE TITLE
usuario fecha lightbox nao cancela pedidoo

### ISSUE THREAD

**Issue by albertobraschi** [mercadopago/cart-magento#168]
pus pra rodar o plugin MP. testei blza.
configurei lightbox tudo certo.
abriu certinho. nao tem opção pro usuario cancelar. fechei e cliquei pra home.
saiu. certo.
não cancelou o pedido. 
vou ver aqui uma alteração sobre isso!

**Comment by gmatsuoka** [comment]
Ola @albertobraschi, tudo bem?

O pedido não é cancelado de acordo com comportamento do checkout e sim com o do pagamento, nesse caso o cliente não chegou a concluir o pagamento e por isso não tem uma atualização de status.

Caso houvesse um pagamento e o mesmo fosse cancelado o pedido seria cancelado corretamente.

Atenciosamente,

Gabriel.

**Comment by cristianoap** [comment]
Seguindo a situação apresentada, vamos considerar:
- um produto com gerenciamento de estoque ativo;
- plugin com configurações globais:
![image](https://cloud.githubusercontent.com/assets/4174411/20203192/5443dd4e-a7ac-11e6-89bd-798d14a76e65.png)

No ato da finalização do processo de checkout, este produto será "reservado" para o cliente enquanto ele não termina o processo de pagamento. Caso venha a ocorrer algum problema ou cancelamento do lightbox, aquele produto ficaria num limbo, pois o processo não foi finalizado, não terá a chance de finalizar e no painel não podemos encerrar este pedido.

Qual seria a maneira mais adequada de evitar esse limbo, cancelar o pedido e reaver o produto?
