### ISSUE TITLE
Bug de moeda

### ISSUE THREAD

**Issue by Dexxtz** [mercadopago/cart-magento#170]
Quando se tem por padrão no magento outra moeda como padrão, passa a ter um bug.

Exemplo: Moeda padrão EURO porem de exibição Real(tanto faz se disponibilizar as 2 moedas ou criar visão para cada moeda tudo tem bug), então digamos que tenho um produto que custe 100 euros, no frontend vai mostrar o valor convertido em reais, na finalização mostra tudo em reais, e no final acrescenta uma frase "Seu cartão de crédito será cobrado em" já é um bug se estiver  usando o clássico, mas enfim ao invés de mandar o valor correto em reais manda o que exibe em euros sem a moeda, ai no mercado pago a pessoa paga R$ 100,00

![sem titulo](https://cloud.githubusercontent.com/assets/7794023/18655796/25b80f58-7ec2-11e6-8ca5-3256663bce0a.png)

**Comment by gmatsuoka** [comment]
Olá @Dexxtz , tudo bem?

O Módulo do Mercado Pago não adiciona essa mensagem. Você não esta utilizando algum outro módulo que faça isso?

Pode enviar a versão do módulo que esta utilizando e se possível o link da loja para que eu possa efetuar alguns testes?

Atenciosamente,

Gabriel.

**Comment by Dexxtz** [comment]
Olá obrigado pelo retorno, comecei a avaliar, debugar etc, e é o magento que faz isso, como só tinha mercado pago instalado achei que fosse ele.

Se a moeda padrão não for Real, na finalização mostra os valores mas envia para os meios de pagamento, na moeda padrão, e o único que tratou certo foi o paypal(moeda padrão euro, frontend real, enviado em euro, exibido em euro na hora de pagar), então seila vocês poderiam dar uma analisada nisso

**Comment by gmatsuoka** [comment]
Olá @Dexxtz,

O Mercado Pago processa apenas em moeda local, por esse motivo é interessante manter a moeda padrão como o Real (no caso do Brasil). 

Atenciosamente,

Gabriel.

**Comment by Dexxtz** [comment]
Eu uso mercado livre latino, que utiliza real, dólar e euro o módulo é excelente mas tem muitas coisas que poderia se pensar para deixar ele melhor é só uma sujestão
