### ISSUE TITLE
Mensaje de error al cancelar pedidos con métodos de pago que no son Mercado Pago

### ISSUE THREAD

**Issue by nmarquev** [mercadopago/cart-magento#176]
No es un error importante ya que a nivel funcional todo se ejecuta bien, pero al querer cancelar un pedido (en estado Pending) desde el Admin de Magento que no fue realizado con Mercado Pago (ejemplo pago en efectivo), devuelve el error: 
"You can only make cancellations on orders whose payment status is Rejected, Pending o In Process
Mercado Pago - Cancellation not made". Luego el pedido queda cancelado, pero de todas formas no debería dar este mensaje ya que el pedido no fue pagado con Mercado Pago.

**Comment by suweed** [comment]
Yo igual tengo ese error, aun no sabe alguien como resolverlo, debugueando un poco vi que faltan indices
$order->getPayment()->getData('additional_information')['status']; el array de additional_information esta vacio

**Comment by fdinapoli-summasolutions** [comment]
Hace unos momentos subimos una actualización del módulo que soluciona este bug.

Quedamos a la espera de comentarios.
