### ISSUE TITLE
Status do pedido não alterna após confirmação do recebimento.

### ISSUE THREAD

**Issue by smarley2** [mercadopago/cart-magento#179]
Olá, no dia 11 deste mês um cliente comprou na loja e pagou com cartão de crédito, recebemos o email do mercadopago informando o recebimento do valor, porém o status na loja não foi alterado.

Pensei que poderia ser alguma modificação no módulo ou algo assim (a loja estava com a versão 1.9.2.2 e uma versão do mercadopago do começo do ano).
Então no final de semana fiz a instalação em uma nova pasta da versão 1.9.3 e a versão do mercadopago aqui do git, a mais atualizada.

Porém ontem um cliente comprou e aconteceu o mesmo, o status não foi alterado.

Existe algum bug conhecido?
Tem uma forma de contornar isto?
Caso tenha interesse e seja útil posso passar os números das transações no mercadopago.

A única solução foi a autenticação manual conforme sugestão do @kinfoxxx.
Mas aí perde totalmente a praticidade do módulo.
https://www.domínio.com.br/mercadopago/notifications/custom?type=payment&data.id=ID_PAGAMENTO

Obrigado.

**Comment by kinfoxxx** [comment]
Boa noite, nada de solução ainda, de cada 10 vendas 9 não se altera o status .

**Comment by smarley2** [comment]
@kinfoxxx Vou tentar rastrear com o log para ver se aparece algum erro.
Já tentou fazer isto?

Para mim todas não estão sendo alteradas.

**Comment by imasson** [comment]
Olá @kinfoxxx @smarley2 eles têm a versão mais recente do plugin?

**Comment by smarley2** [comment]
Sim, eu instalei a versão mais recente do Magento 1.9.3 e no mesmo instante fiz o download aqui do git da última versão do módulo.

**Comment by imasson** [comment]
Ok, e você pode confirmar o recebimento de notificações no dominio publico?

**Comment by smarley2** [comment]
Boa tarde @imasson desculpe não entendi a sua questão.
Para identificar os pagamentos eu acesso do meu navegador https://www.60hz.com.br/mercadopago/notifications/custom?type=payment&data.id=ID_PAGAMENTO

**Comment by imasson** [comment]
Você tem arquivo de log as notificações? mercadopago-notification.log

**Comment by smarley2** [comment]
Sim @imasson, segue o link do arquivo (não consegui anexar no post): https://www.60hz.com.br/downloads/mercadopago-notification.log
Lembrando que após as compras todas foram identificadas manualmente.

**Comment by smarley2** [comment]
Pelo que entendi do log ocorre o seguinte:
as 2016-12-12T17:16:33+00:00 DEBUG ou 2016-12-12T17:17:00+00:00 DEBUG (não sei dizer qual é o correto) houve um novo pedido na loja, e este foi identificado manualmente as 2016-12-12T17:50:09+00:00 DEBUG através do ID manualmente verificar no MP, 2488551619.

Pensei que talvez as minhas informações de configuração do usuário do MP não estivessem corretas para ele não encontrar o ID, porém aí eu não estaria recebendo o dinheiro, certo?
De qualquer forma acabei de conferir o Public Key e Access Token e batem com o do MP.

**Comment by smarley2** [comment]
Alguma ideia @imasson ?

Obrigado.
