### ISSUE TITLE
Success adjustment and returned info translate

### ISSUE THREAD

**Issue by davirs** [mercadopago/cart-magento#181]
Hi! There is some things to solve at success page.

1 - The success page needs a DIV "container" to align to center. Now is aligned at left broken the magento layout.
![screenshot_48](https://cloud.githubusercontent.com/assets/4355062/20403680/eb9d18a4-ace8-11e6-85c6-f021168b7b93.png)

2 - Translate payment info and variables.. My language is portuguese.. So we need a way to translate this variables displayed in english ..

![screenshot_50](https://cloud.githubusercontent.com/assets/4355062/20403695/fa80ca32-ace8-11e6-918d-0c3610497500.png)

**Comment by imasson** [comment]
This will be fixed in next plugin version

**Comment by niketedm** [comment]
Alguna actualización de esto? Ya se puede modificar por csv?

**Comment by imasson** [comment]
Hola,
Los cambios se veran reflejados en la proxima release.

Saludos,
