### ISSUE TITLE
Problemas com Cupom de Desconto

### ISSUE THREAD

**Issue by Forbiddeen** [mercadopago/cart-magento#182]
Olá Senhores,

Boa tarde.

Alguém pode me ajudar? Estou usando o MERCADOPAGO com o módulo OSC 6. Acontece que quando eu insiro um código de desconto no CHECKOUT, as parcelas não se atualizam, na verdade elas somem. Podem em ajudar?

O mesmo acontece quando eu escolho um desconto automático no boleto bancário. Quando meu cliente seleciona o boleto bancário, automaticamente aplica o desconto, porém quando eu volto para o MERCADOPAGO o valor continua disponível, e no mercadopago não tem desconto. Alguém pode me auxiliar?

**Comment by Forbiddeen** [comment]
Notei que isso acontece exclusivamente com o MERCADOPAGO.

Eu coloco o desconto APENAS no BOLETO e todos os outros métodos de pagamento o removem, menos o mercadopago.

**Comment by Forbiddeen** [comment]
Se alguém tiver alguma sugestão, literalmente a regra de desconto não se aplica ao MERCADOPAGO caso ela seja automática.

**Comment by imasson** [comment]
Hola @Forbiddeen !
você tem a opção OSC ativada dentro do módulo MercadoPago?
![image](https://cloud.githubusercontent.com/assets/8289723/20497486/1fb8fee2-b008-11e6-9ce4-3bba9eedeb04.png)

**Comment by Forbiddeen** [comment]
Olá, 

Tenho sim, devo desativa-la?

**Comment by Forbiddeen** [comment]
Ninguém? Mesmo eu aplicando a regra de desconto SOMENTE NO MERCADO PAGO, não funciona. Ele não reconhece que tem uma regra nele.
