### ISSUE TITLE
Desabilitar financing cost do Pedido

### ISSUE THREAD

**Issue by Forbiddeen** [mercadopago/cart-magento#183]
Olá,

Gostaria de saber como eu desabilito o valor total das parcelas. No caso meu cliente parcelou em diversas vezes, mas esse valor é pago para o MERCADOPAGO, não para nós. Quero remove-lo, pois acaba fazendo confusão com a expedição que emite as notas fiscais, além de dar um deficit em nossos caixas, já que temos um valor X em estoque e acabamos faturando Y (X+Juros).

**Comment by imasson** [comment]
Hola @Forbiddeen !
você pode desativar a opção de aqui
![image](https://cloud.githubusercontent.com/assets/8289723/20497560/621eb916-b008-11e6-92c0-6236974be178.png)

**Comment by Forbiddeen** [comment]
Olá Imasson,

Obrigado!

Eu fiz essa ação, porém a única ação foi não exibir o campo com o total, mas o valor apareceu em um pedido que fiz após desabilitar essa função.

http://nimb.ws/tDUeLs

1. Produto
2. Total da Compra
3. Produto + Taxas

**Comment by gmatsuoka** [comment]
Olá @Forbiddeen 

Isso já foi corrigido, por favor, atualize o módulo.
