### ISSUE TITLE
Uso del método desde el backend

### ISSUE THREAD

**Issue by barbanet** [mercadopago/cart-magento#187]
Me tocó una auditoría en la cual revisando los logs encontré:

> CRIT (2): Not valid template file:adminhtml/base/default/template/mercadopago/standard/form.phtml

Esto se debe, entiendo, a que el model MercadoPago_Core_Model_Standard_Payment hace uso del bloque mercadopago/standard_form.
Allí se llama al phtml mercadopago/standard/form.phtml.

Al ser ejecutado en el backend genera el error. Quizás, al model se le podría indicar:

`protected $_canUseInternal = true;`

De ésta forma no aparecería como opción en el backend.
Otra alternativa es recrear los phtmls dentro del theme adminhtml/adminhtml.

**Comment by esavignone** [comment]
Hola Damián,

Gracias por el feedback, vamos a revisarlo!

Saludos!

**Comment by barbanet** [comment]
Vi que esto ya se llevó a master. Cierro.
