### ISSUE TITLE
Calculador de cuotas bajo HTTPS

### ISSUE THREAD

**Issue by barbanet** [mercadopago/cart-magento#194]
Estoy usando el calculador en la página de producto y el sitio está bajo HTTPS.
El problema que tengo es que las imágenes de las tarjetas vienen por HTTP y no encuentro una forma por configuración de pedir HTTPS.

Ejemplo:

http://img.mlstatic.com/org-img/MP3/API/logos/tarshop.gif

Debería ser:

https://img.mlstatic.com/org-img/MP3/API/logos/tarshop.gif

¿Hay forma de forzar esas llamadas?

**Comment by ctorres1** [comment]
Hola, 

No existe una configuración que permita optar entre una u otra opción, pero si la hay una forma de modificar la respuesta por código. 
Para solucionarlo se debe cortar la primer parte de la ruta de las imágenes, de forma tal que sean llamadas con http o https en función la pag que las llama.

Te paso el link al repo local sobre el que trabajo, donde está la solución por si queres modificarlo antes de que salga la nueva versión del modulo. https://github.com/SummaSolutions/cart-magento/compare/develop...ctorres1:T_975 

Espero te sea util mi respuesta.
Saludos

**Comment by barbanet** [comment]
Gracias, funcionó (me tiré a ver si había una forma más elegante)
:-)
