### ISSUE TITLE
Atualizem as versões PHP

### ISSUE THREAD

**Issue by LuizSantos1** [mercadopago/cart-magento#197]
Por favor, atualizem as versões PHP acima do que está atualmente.
A maioria dos hosting já trabalham com php 5.6 ou superior, inclusive rodando em php 7 ou 7.1

Ou seja, temos versões atualizadas da extensão do MercadoPago, no entanto, a versão do
php a torna incompatível com a maioria das instalações 1.9 ou superior.

**Comment by LuizSantos1** [comment]
Outra coisa, há a opção de editar a imagens dos cartões que aparecem no pop up?
Pois essas imagens são um tanto quanto antigas, então seria interessante poder modificá-las.

**Comment by gmatsuoka** [comment]
@LuizSantos1 

Atualmente o Magento 1.x não possui suporte a versão 7 do PHP, apenas a versão 2.x do Magento.
Sobre o ponto das imagens, a quais imagens você se refere?

**Comment by LuizSantos1** [comment]
@gmatsuoka 
Olá, tudo bem?
Acredito que minha mensagem não foi bem interpretada, não disse que Magento 1.x é compatível com PHP7, disse para atualizarem para versões do PHP 5.6 ou superior, uma vez que a maioria dos hostings já trabalham com versões 5.6 ou acima. 

Ainda que não oficialmente, é relativamente fácil tornar Magento 1.9.x compatível instalando o plugin da Inchoo, inclusive tenho o meu site assim e com o MercadoPago instalado e funcionando.

Com relação a minha primeira solicitação, parece que resolveram o problema, já que vejo uma atualização no MagentoConnect falando sobre isso, era algo bem chato, já que todas as vezes tinha que modificar meu "htaccess" para tornar minha instalação compatível com versões PHP 5.3, 5.4 e a grande maioria das pessoas não sabem fazer isso. À princípio, isso já foi contornado. 

Com relação à minha 2a solicitação, que é uma questão mais estética, mas que considero relevante, é a questão das imagens das bandeiras que aparecem no pop up do simulador de parcelas na página do produto. Mando em anexo um screenshot mostrando as bandeiras neste link: https://goo.gl/EwvmDa

Att,
Luiz Santos
