### ISSUE TITLE
Problemas com Inovarti OSC

### ISSUE THREAD

**Issue by lucasPiovesan** [mercadopago/cart-magento#201]
Boa tarde.

Possuo uma loja magento com o checkout Inovarti OSC instalado, e fui instalar o módulo do Mercado Pago nele. Quando instalei notei que deu conflito, as formas de pagamento não abriam. 

Tirei o checkout da Inovarti e testei com o nativo do magento, e funcionou. 

Pensando que era alguma customização em minha loja, baixei uma aplicação magento zerada, e a configurei com o checkout da Inovarti e Mercado Pago. Porém não funcionou novamente. 

Olhando a documentação do Mercado Pago no git, está dizendo que tem compatibilidade com o checkout da Inovarti, porém não é isso que está acontecendo, podem verificar por favor?

Possuo outras lojas magento, com uma versão mais antiga do mercado pago utilizando o módulo da inovarti de checkout, e essa versão mais antiga funciona perfeitamente. Número da versão: 2.3.0

Alguma atualização realizada fez com que essa compatibilidade deixasse de funcionar. Podem verificar?

**Comment by FelipeMartinin** [comment]
Mesmo problema aqui =/ Magento 1.9.2.4

**Comment by lucasPiovesan** [comment]
@FelipeMartinin o que notei também é que esse problema ocorre na versão 1.9 apenas, pois testei na versão 1.8 funcionou normalmente com o OSC instalado.

Então da pra se presumir que é algum conflito apenas nas versões 1.9.

**Comment by gmatsuoka** [comment]
@lucasPiovesan, qual versão do módulo você esta utilizando? recentemente liberamos uma versão corrigindo esse bug.

**Comment by LuizSantos1** [comment]
@gmatsuoka 
Mesma coisa aqui, só que com o OSC da Moip, que pra mim é o melhor do mercado. 
https://www.magentocommerce.com/magento-connect/moip-transparente-oficial.html

Eu estava usando a versão 2.4.1 com a opção de parcelamento em pop up na página do produto (fiz umas modificações para chamar o código java numa imagem específica), ficou muito bom. 

Aí veio as novas regras do boleto e caí na besteira de atualizar. 

Parou de funcionar tudo, tanto o pop up de parcelamento (simulador de parcelamento) quanto 
o checkout em si. Pra piorar, não posso alterar muito a configuração, já que meu backend está com problemas com módulos que usam jquery (fica super bonito, mas se vocês soubessem a quantidade de problema, não usariam isso, manteriam a configuração simplificada como na versão 0.02) 

Resume da ópera, já restaurei o site para a versão 2.4.1 que estava funcionando e nada! Tive que reinstalar a versão 0.02 e desabilitar o método de pagamento via boleto. 

Tentem evitar usar jquery para configurações no admin, isso trás um monte de problemas e conflitos tanto com módulos OneStepCheckout quanto com outros módulos de pagamento.

**Comment by FelipeMartinin** [comment]
@LuizSantos1 Já tentou mudar todos os objetos jQuery dos módulos que são carregados no checkout? Exemplo: todo jquery que está sendo usado na página do checkout, substituir o $('') por jQuery(''). Pode ser algum conflito de biblioteca.

**Comment by LuizSantos1** [comment]
Olha, pra dizer a verdade, não saberia como adaptar e reconfigurar todas as bibliotecas jQuery
de todos os módulos que tenho no Checkout do site. E juntamente comigo, cerca de 85/90% das pessoas
que usam o módulo. Acredito que o processo, deveria ser o inverso. Ou seja, o módulo tentar evitar criar
meios de evitar conflitos desativando algumas funções de jQuery como há em alguns módulos.

Ou seja, o módulo do MercadoPago se adaptar ao site, e não o contrário. E já há uma versão que não
entra em conflito, que é a versão 0.02 e explico abaixo o que pode estar gerando esse problema.

A configuração no admin panel (sistema/configuração/formas de pagament/MercadoPago, se dá 
da seguinte forma na versão 0.0.2:
Você preenche os campos em "MercadoPago Configuration" e ativa "MercadoPago Standard - CreditCard, Ticket e Account Money",

Salva e pronto. O módulo funciona perfeitamente no site, sem qualquer problema. 


Nas NOVAS VERSÕES, vocês introduziram dropdowns (ou toggles) que supostamente deveriam abrir 
as opções de configurações ao clicar no botão "Configurar/Fechar", pois bem, esse botão NÃO FUNCIONA. Pelo menos
não no meu site. Aí fico sem condições de configurar o módulo corretamente. 

Eu até contornava isso com uma "gambiarra", instalando o módulo antigo (0.0.2) congigurava tudo e atualizava
para a versão mais atual. Infelizmente, isso parou de funcionar. 

Creio que seria mais produtivo, numa futura versão, retornar a configuração aos moldes antigos, sem esses botões "Configurar/Fechar"
no admin. Pois é mais fácil adaptar o módulo ao site do que o contrário, pois teríamos que reconfigurar tudo de novo,
a cada atualização do site ou dos outros módulos. 

Esse mesmo problema ocorreu com o módulo de pagamento "Gerencianet", eu simplesmente desativei para evitar o estresse.

**Comment by lucasPiovesan** [comment]
@gmatsuoka problema resolvido, instalei a nova versão a um tempo atrás e está ok! Obrigado!
