### ISSUE TITLE
Mercado Envios - Divisão de Pacotes

### ISSUE THREAD

**Issue by mateus007** [mercadopago/cart-magento#206]
Olá, gostaria de saber se o módulo terá suporte a divisão de pacotes pois em alguns casos, quando há muitos produtos no carrinho as dimensões do pacote excedem o limite e impedem o uso do método de frete.

**Comment by gmatsuoka** [comment]
Olá @mateus007, 

Atualmente o módulo não possui suporte a essa funcionalidade.
