### ISSUE TITLE
Página de erro na digitação

### ISSUE THREAD

**Issue by radamiBR** [mercadopago/cart-magento#212]
Uso a versão 2.7.10 no magento 1.9.0.1

Quando cliente digita errado exemplo data, ano ou código de segurança do cartão de crédito.

E finalizado a compra e vai para página mercadopago/checkout/page "Não foi possível processar o pagamento".

Como foi um erro de digitação não tem opção na pagina checkout um JS dar erro ao cliente para o mesmo fazer a correção na pagina checkout sem finalizar a compra.

Pois todo erro de digitação e finalizado compra como pedido cancelado e tirado do estoque da loja magento.

**Comment by gmatsuoka** [comment]
Olá @radamiBR ,

Quando o erro de digitação está fora do padrão, o módulo mostra uma mensagem de validação diretamente no formulário. Exemplos:
- Data de validade que já passou e o cartão já está expirado (ex: 01/17 e 02/17).
- Código de segurança com menos de 3 digitos

Caso esses dados estejam "corretos", porém não estão de acordo com as informações do cartão. O pagamento será criado, porém recusado. Logo o processo do módulo esta correto.
