### ISSUE TITLE
Form não aparece

### ISSUE THREAD

**Issue by lmarquine** [mercadopago/cart-magento#217]
Na página do checkout o Módulo não exibe o form, já copiei a pasta template e layout do MP dentro da pasta tema e adicionei todos os .JS através do checkout.xml, debugando, todos os .JS estão carregados e o Mercado Pago aparece nas opções de pagamento porém ao seleciona-lo não aparece o form para inserir os dados do cartão. O que pode ser? Pode ser pelo fato da página estar sem o SSL?

![image](https://user-images.githubusercontent.com/8151683/30000473-d3902faa-9043-11e7-9dcb-e74ab7895db6.png)

**Comment by gmatsuoka** [comment]
@lmarquine 
Sim, pode ser pelo fato de estar sem SSL e também pode ser que o Mercado Pago esteja desabilitado na opção System > Configuration > Advanced > Advanced.
