### ISSUE TITLE
No está disponible la extensión para versión Magento 1.9.x

### ISSUE THREAD

**Issue by imaginationcg** [mercadopago/cart-magento#227]
Estimados: No se encuentra disponible en Magento Connect la extensión para las versiones de Magento 1.9.x. Hay alguna forma de obtener dicha extensión para integrar a una tienda que utiliza dicha versión?.

**Comment by barbazul** [comment]
Podes descargarla desde este repositorio. En la seccion de Releases tenes los descargables.

https://github.com/mercadopago/cart-magento/releases
