### ISSUE TITLE
No funciona para Magento 2.1.7

### ISSUE THREAD

**Issue by durabite** [mercadopago/cart-magento#228]
Instale el modulo según los pasos a seguir, pero al activarlo me sale este error.

Something went wrong while saving this configuration: Notice: Undefined index: mercadopago/magento2-plugin in /opt/bitnami/apps/magento/htdocs/app/code/MercadoPago/Core/Helper/Data.php on line 488

Trate de usarlo aun con el error pero el carrito desaparece, es decir no carga nada en el checkout, al desactivarlo vuelve a funcionar. Mi sitio es baytu.mx Alguna idea?

**Comment by barbazul** [comment]
Este repositorio corresponde al módulo de Magento 1.x


Por favor postea tu issue en el repositorio de M2 https://github.com/mercadopago/cart-magento2
