### ISSUE TITLE
No se puede probar subscripciones en sandbox ni con tarjetas de prueba

### ISSUE THREAD

**Issue by joae** [mercadopago/cart-magento#230]
No logro completar el flujo de una suscripcion (recurrent profile).
Opcion test 1) Si lo hago en modo sandbox, aparecen comboBox para elegir la tarjeta de credito según status deseado. Arroja error ups algo ocurrio.

Opcion test 2) Sandbox off, usuarios de compra y vendedor de prueba usando tarjeta de prueba segun: https://www.mercadopago.com.ar/developers/en/solutions/payments/basic-checkout/test/test-payments/

Solo se aprueba el debito, nunca se ejecuta un pago y por ende no se envia la notificacion para ver que se cree la order correspondiente a ese recurring profile.

Cómo se puede probar el feature completo?

gracias

**Comment by gmatsuoka** [comment]
Lo ideal es utilizar usuarios de tests en ambiente de producción, pues el sandbox no es muy confiable para este tipo pruebas, ya que es un poco inestable.

Otro punto importante es que es necesario configurar url de notificación en su cuenta de Mercado Pago.
