### ISSUE TITLE
Desconto Boleto

### ISSUE THREAD

**Issue by cfgalvani** [mercadopago/cart-magento#231]
O desconto do boleto não é mais aplicado no pedido. Ele diz que o cupom está ok, recarrega o resumo do pedido mas não aplica o desconto.
Checkout: OSC 6 Brasil
Mercado Pago: 2.10.0

**Comment by gmatsuoka** [comment]
@cfgalvani 

No painel de configurações está configurado para mostrar os descontos no detalhe do pedido? quando você fala "recarrega" é reload na pagina ou em uma div?
