### ISSUE TITLE
Notificación con historial de Pagos

### ISSUE THREAD

**Issue by jpmayoral** [mercadopago/cart-magento#239]
Buenas! Hace un par de semanas detectamos que en nuestros sitios de Magento 1.9.x con la última versión del módulo de MercadoPago tenemos órdenes que pasan de Pago Aprobado a Pago Rechazado debido a notificaciones de MercadoPago que antes no llegaban.

Por lo q vemos en el historial de comentarios de la orden llegó primero una notificación de pago rechazado, después una de pago aprobado y por último una notificación con el historial de los dos anteriores (esta notificación es la q genera inconsistencias y deja la orden en pago rechazado nuevamente).

Notificación automática de Mercado Pago: El pago fué rechazado.
Número de Pago: 3121125651
Estado: rejected
Detalle del Estado: cc_rejected_call_for_authorize

Notificación automática de Mercado Pago: El pago fué aprobado.
Número de Pago: 3120920365
Estado: approved
Detalle del Estado: accredited

**Notificación automática de Mercado Pago: El pago fué aprobado.
Número de Pago: 3120920365 | 3121125651
Estado: approved | rejected
Detalle del Estado: accredited | cc_rejected_call_for_authorize**

Si pueden darme alguna guia de dónde puede estar el problema seria de gran ayuda. 

Muchas gracias! Saludos!

**Comment by gmatsuoka** [comment]
Actualice el módulo a la versión más actual, ya se ha fijado este problema.
