### ISSUE TITLE
Botón de Magento Express no funciona

### ISSUE THREAD

**Issue by molanovsky** [mercadopago/cart-magento#24]
Tengo la versión 1.7.0.2 de Magento, instalé el módulo y el botón de Magento Express en el Shopping Cart figura, pero parece no tener una acción asignada (en las demás instancias lo tengo deshabilitado directamente)

**Comment by esavignone** [comment]
Hola @molanovsky ,

El ticket será cerrado, por favor reabrir si el problema persiste.

Muchas gracias!
