### ISSUE TITLE
Importar CPF

### ISSUE THREAD

**Issue by FelipeMartinin** [mercadopago/cart-magento#243]
No momento estou fazendo apenas uso do lightbox, sem o transparente. Como o módulo retorna o CPF do cliente para o bloco "informações de pagamento" na página do pedido, no backend, gostaria de saber como injetar também esse dado no cadastro do respectivo cliente, no campo VAT por exemplo, para evitar divergências entre o que foi informado no site e no pagamento, e facilitar exportar esses dados para emitir a nota fiscal.

**Comment by gmatsuoka** [comment]
Atualmente o módulo não suporta esse comportamento, você poderá customizar o módulo para que funcione dessa forma.
