### ISSUE TITLE
Problemas con Multistore Base Currency USD Store View COP

### ISSUE THREAD

**Issue by jloronoz** [mercadopago/cart-magento#244]
Hola a todos buen dia, tengo un problema con una tienda que tiene Base Currency USD y Store View  es en Moneda local Colombiana COP, usando checkout standard al agregar la tarjeta de credito muestra los valores en USD como pueden ver aqui : https://screencast.com/t/CbaACbTZgSM

Cuando el cliente hace el pago el log genera la siguiente linea: create preference result - {"status":400,"response":{"message":"unit_price must be a integer","error":"invalid_items","status":400,"cause":[]}}

Que puedo hacer para solucionar este error? Alguien me puede ayudar por favor.

Tengo Mercadopago Version: 2.11.1 : https://screencast.com/t/AMTR4UOc
Magento CE Version:  1.9.3.1

**Comment by gmatsuoka** [comment]
Actualmente el módulo no soporta la conversión de monedas.
