### ISSUE TITLE
Status não altera no Magento

### ISSUE THREAD

**Issue by Hzc2500** [mercadopago/cart-magento#246]
Estamos tendo alguns problemas referentes aos status dos pedidos, que estão sendo aprovados no mercado pago porém alguns não estão voltando como pagos no magento.

O módulo está atualizado e verifiquei na documentação que as notificações são reenviadas da seguinte maneira:
1- Tentativa após 5 segundos.
2- Tentativa após 45 minutos.
3- Tentativa após 6 horas.
4- Tentativa após 2 dias.
5- Tentativa após 4 dias.

Porém mesmo após o 4 dia ele não está alterando.

**Comment by FelipeMartinin** [comment]
Está acontecendo isso com todos os pedidos? Pois notei que estou tendo esse problema apenas com pedidos que nas primeiras tentativas de pagamento deu erro.

**Comment by Hzc2500** [comment]
@FelipeMartinin Não são todos os pedidos, por exemplo no dia 20/01/2018 de 13 pedidos 5 não tiveram os status alterado.
Já no dia 21/01/2018 de 17 pedidos 5 também não tiveram os status alterado.
Porém no dia 22/01/2018 de 39 pedidos 15 não alteraram.

Não reparei direito, porém acredito que os pedidos parecem estar alterando no maximo até a 3 tentativa, depois as outras 2 tentativas nunca troca.

**Comment by tiagooctp** [comment]
@Hzc2500 @FelipeMartinin 
O mesmo está acontecendo em alguns pedidos na loja de um de nossos clientes.
Ao analisar alguns logs que inseri, verifiquei que quando o mercado pago retorna as informações do pedido para o Magento, este pedido não é encontrado. Me parece que o Mercado Pago está enviando as informações antes mesmo do pedido ser criado no Magento.

**Comment by FelipeMartinin** [comment]
@Hzc2500 @tiagooctp  Bom, no meu caso o padrão é esse: alguns pedidos dos quais as primeiras tentativas de pagamento deram erro, mas depois acabou sendo aprovado, não está alterando no Magento. 

Agora é legal deixar isso bem especificado e cobrar para os devs do MP.

**Comment by Hzc2500** [comment]
@FelipeMartinin @tiagooctp 

Pelo que analisei é o que está acontecendo aqui também, ele envia a notificação antes de criar o pedido e retorna 200, por isso não acontece as outras notificações que poderiam corrigir o pedido

**Comment by gmatsuoka** [comment]
Atualize o módulo para a versão mais atual, já foi realizado alguns ajustes no módulo que corrige esse comportamento.
