### ISSUE TITLE
Error en Calculador de Cuotas (2.11.2)

### ISSUE THREAD

**Issue by jpmayoral** [mercadopago/cart-magento#250]
Buenas! En la última versión del módulo al activar el calculador de cuotas en PDP y Carrito hay un error de JavaScript ya que se está llamando a la libreria TinyJ la cual no existe en el módulo.

![selection_005](https://user-images.githubusercontent.com/496740/37403086-7541fc88-276c-11e8-9378-41d3974df172.png)

**Comment by francosabolo** [comment]
Hola @jpmayoral, yo tuve el mismo error y lo solucione descargando estas librerias yendo al tag 2.7 en este mismo repositorio:

https://github.com/mercadopago/cart-magento/blob/2.7.12/1.6.x-1.9.x/js/mercadopago/tinyJ.js
https://github.com/mercadopago/cart-magento/blob/2.7.12/1.6.x-1.9.x/js/mercadopago/tiny.min.js

Saludos.

**Comment by gmatsuoka** [comment]
Actualiza el módulo a la versión más actual, este error ya se ha fijado.
