### ISSUE TITLE
Problem with the extension manager and mercadopago

### ISSUE THREAD

**Issue by webstower** [mercadopago/cart-magento#252]
I want to install new extension in magento, but, when I try to enter to the extension manager, magento shows the red error with mercadopagos and github and no operations can I make in this manager...

I generated the access token in github and try two solutions without success:

1. Run the following command from ssh: 
composer config --global github-oauth.github.com <TOKEN>
(nothing happens) I don´t see the supposed auth.json file thats claim other users thats create that commnad

2. In my composer.json added the following config section to the mercadopagos require.
"repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        {
            "type": "vcs",
            "url": "https://github.com/mercadopago/cart-magento2",
            "config": {
                "github-oauth": {
                    "github.com": <token>
                                }
                      }
        }
    ]

Any Ideas?
![captura--magento-extension-manager](https://user-images.githubusercontent.com/36306611/37776458-16f66c46-2dc4-11e8-9097-e00ab8eddc8e.png)

**Comment by goncalocruz77** [comment]
Já tentou mandar nesta página?
https://github.com/mercadopago/cart-magento2

Ela é mais específica para este problema. E também, te abre outra opção de retorno.
