### ISSUE TITLE
Erro página de sucesso

### ISSUE THREAD

**Issue by goncalocruz77** [mercadopago/cart-magento#255]
Estou com erro na página de sucesso da loja após comprar pelo Mercado Pago.

a URL em questão é a seguinte: https://www.magazinedesign.com.br/mercadopago/checkout/page/

Já quando finalizo por outras formas de pagamento ela aparece normal e com a URL: https://www.magazinedesign.com.br/checkout/onepage/success/

O mesmo acontece quando vou finalizar pela forma Classica (Usando LightBox): https://www.magazinedesign.com.br/mercadopago/pay/

Alguém já teve o mesmo problema? É algo nas configurações? Tenho que subir algum arquivo do tema nas pastas do Mercado Pago?

Quando altero a opção Usar página de sucesso Mercado Pago para não ele mostra a página de confirmação do magento, sem quebrar, mas não tem o link para boleto, só a confirmação da compra.

Se alguém quiser testar pode fazer a compra por boleto.

Obrigado pela ajuda.

**Comment by gmatsuoka** [comment]
Caso você queira utilizar a pagina de sucesso do Magento, você terá que personalizar o módulo para que mostre o botão do boleto. Caso contrario, só utilizando a pagina de sucesso do Mercado Pago que terá essa opção.

O módulo não consegue contemplar a pagina de sucesso do Magento, pois cada um personaliza da sua forma e em varios casos que testamos não estava funcionando. Por esse motivo criamos essa pagina para que sempre apareça o botão do boleto.
