### ISSUE TITLE
Ocorreu um erro ao processar o pagamento

### ISSUE THREAD

**Issue by davirs** [mercadopago/cart-magento#256]
O pedido é finalizado normalmente, aparece no painel adminsitrativo porém não vai para tela de sucesso, vai para a tela padrão do magento de erro no pagamento...
http://prntscr.com/j31fx2

dentro do pedido o status varia de acordo com o pedido, como revisão manual etc

Já havia ocorrido este erro antes e o  suporte já havia corrigido. Voltou a ocorrer nestes  últimos dias.

como proceder?

**Comment by gmatsuoka** [comment]
Normalmente ocorre esse erro quando o pagamento não é criado, nos arquivos de logs existe algum erro retornado da API?
