### ISSUE TITLE
Pedido não integra no Magento

### ISSUE THREAD

**Issue by higuoliveira98** [mercadopago/cart-magento#258]
Bom dia,

Estou tendo um problema, onde meu cliente efetua uma compra na loja. Ao clicar no botão de Finalização de Compra, não vai para a página de Sucesso, os itens continuam no carrinho, porém o pagamento é confirmado junto ao Mercado Pago e não há registro nenhum do pedido no Magento. O problema ocorre apenas em transações com Cartão de Crédito, sabe me dizer o porque ocorre o problema ?

**Comment by gmatsuoka** [comment]
Normalmente esse erro ocorre quando o tempo de resposta do seu servidor é muito alto e por esse motivo o Magento cancela a requisição e retorna da onde "parou", porém o fluxo de pagamento já foi finalizado.

Esse tipo de comportamento é dificil de ser trato no módulo, pois o "trabalho" dele já foi finalizado.
Minha sugestão é você analisar os tempos de respostas do seu servidor e ver se existe algo a ser otimizado.
