### ISSUE TITLE
Extension 1.9 = Not working

### ISSUE THREAD

**Issue by PauloBoaventura** [mercadopago/cart-magento#259]
### //PT/BR//
Estou tendo o mesmo problema...
Ele estava funcionando perfeitamente...
Mas apos a atualizacao do magento para 1.9.3.8, ele esta dando este erro...
Tentei desistalar pelo Magento Conecct e instalar novamente...
apaguei as pastas como indica e instalei a versão 2.2.2 (MercadoPago).
Mas mesmo assim, os erros são os mesmos...
O pior que não é possivel configurar nenhum tipo de pagamento pois nas configurações do mesmo apresenta os seguintes erros...
==================================
race:
#0 /var/www/vhosts/SITE/httpdocs/includes/src/MercadoPago_Lib_RestClient.php(92): MercadoPago_Lib_RestClient::exec('GET', '/item_categorie...', NULL, 'application/jso...', Array)
#1 /var/www/vhosts/SITE/httpdocs/includes/src/MercadoPago_Core_Model_Source_CategoryId.php(24): MercadoPago_Lib_RestClient::get('/item_categorie...')
#2 /var/www/vhosts/SITE/httpdocs/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(463): MercadoPago_Core_Model_Source_CategoryId->toOptionArray(false)
#3 /var/www/vhosts/SITE/httpdocs/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#4 /var/www/vhosts/SITE/httpdocs/includes/src/Mage_Adminhtml_Block_System_Config_Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#5 /var/www/vhosts/SITE/httpdocs/includes/src/Mage_Adminhtml_Block_System_Config_Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#6 /var/www/vhosts/SITE/httpdocs/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#7 /var/www/vhosts/SITE/httpdocs/includes/src/__default.php(14339): Mage_Adminhtml_System_ConfigController->editAction()
#8 /var/www/vhosts/SITE/httpdocs/includes/src/__default.php(18831): Mage_Core_Controller_Varien_Action->dispatch('edit')
#9 /var/www/vhosts/SITE/httpdocs/includes/src/__default.php(18361): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /var/www/vhosts/SITE/httpdocs/includes/src/__default.php(21317): Mage_Core_Controller_Varien_Front->dispatch()
#11 /var/www/vhosts/SITE/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /var/www/vhosts/SITE/httpdocs/index.php(83): Mage::run('', 'store')
#13 {main}
===========================================================

Peço a ajuda de todos e tambem dos Desenvelopers:
 @go-loco
@jsotuyod
@sebagun
@thiagocaggiano
@tomidelucca

Agradeço desde já!

**Comment by gmatsuoka** [comment]
Esta ocorrendo esse erro pois o módulo não esta conseguindo se comunicar com as APIs do Mercado Pago, isso ocorre devido a configurações do servidor.

Minha sugestão é você validar se esta faltando algum certificado ou algo do tipo.
