### ISSUE TITLE
Merchant order null

### ISSUE THREAD

**Issue by tomasgtz** [mercadopago/cart-magento#260]
Hola,

ya instalé y configuré el módulo en Magento.
Ya tengo los usuarios de prueba
Ya creé un api para recibir las notificaciones de pago.
Ya me llegan, pero al consultar en esta direccion los datos del pago
https://api.mercadopago.com/v1/payments/3728575644?access_token=APP_USR-6277525902404186-051513-8561413cf4051e90bb34f35bd56fd31a-321536589

El dato de order viene vacio... sin él no puedo traer informacion del arreglo 
$merchant_order_info["response"]["payments"]

¿Que error tengo?
Pareciera como si magento no le mandara el numero de la orden a mercadopago

{
    "acquirer_reconciliation": [],
    "statement_descriptor": null,
    "captured": true,
    "date_last_updated": "2018-05-15T09:55:39.000-04:00",
    "merchant_account_id": null,
    "payer_id": 321536589,
    "issuer_id": null,
    "description": "Ingreso de dinero",
    "transaction_amount": 1500,
    "card": {},
    "transaction_details": {
        "total_paid_amount": 1500,
        "acquirer_reference": null,
        "verification_code": "3073901860",
        "payment_method_reference_id": "30739018601",
        "net_received_amount": 0,
        "financial_institution": "641375",
        "payable_deferral_period": null,
        "installment_amount": 0,
        "external_resource_url": "https://www.mercadopago.com/mlm/payments/atm/helper?payment_id=3728575644&payment_method_reference_id=3073901860&caller_id=321536589&hash=89c01242-b684-4fdb-af6e-976d4368e43d",
        "overpaid_amount": 0
    },
    "client_id": "3810498426554826",
    "coupon_amount": 0,
    "metadata": {},
    "money_release_schema": null,
    "collector_id": 321536589,
    "status": "pending",
    "financing_type": null,
    "processing_mode": "aggregator",
    "status_detail": "pending_waiting_payment",
    "transaction_id": null,
    "installments": 1,
    "internal_metadata": {},
    "refunds": [],
    "payment_type_id": "atm",
    "counter_currency": null,
    "profile_id": null,
    "payer_tags": [],
    "reserve_id": null,
    "coupon_id": null,
    "shipping_amount": 0,
    "fee_details": [],
    "acquirer": null,
    "date_created": "2018-05-15T09:55:39.000-04:00",
    "id": 3728575644,
    "collector": {
        "id": 321536589,
        "first_name": "Test",
        "phone": {
            "extension": null,
            "area_code": "01",
            "number": "1111-1111"
        },
        "email": "test_user_77226274@testuser.com",
        "identification": {
            "number": "11111111111",
            "type": "IFE"
        },
        "last_name": "Test"
    },
    "date_of_expiration": null,
    "money_release_days": null,
    "order": {},
    "external_reference": null,
    "available_actions": [
        "cancel"
    ],
    "application_id": 3810498426554826,
    "marketplace": "NONE",
    "merchant_number": null,
    "call_for_authorize_id": null,
    "risk_execution_id": null,
    "api_version": "2",
    "currency_id": "MXN",
    "sponsor_id": null,
    "deduction_schema": null,
    "payment_method_id": "bancomer",
    "additional_info": {},
    "site_id": "MLM",
    "binary_mode": false,
    "operation_type": "account_fund",
    "differential_pricing_id": null,
    "money_release_date": null,
    "payer": {
        "id": "321536589",
        "first_name": "Test",
        "phone": {
            "extension": null,
            "area_code": "01",
            "number": "1111-1111"
        },
        "email": "test_user_77226274@testuser.com",
        "identification": {
            "number": "11111111111",
            "type": "IFE"
        },
        "last_name": "Test",
        "entity_type": null,
        "type": "registered"
    },
    "notification_url": null,
    "transaction_amount_refunded": 0,
    "collector_tags": [],
    "authorization_code": null,
    "date_approved": null,
    "live_mode": true
}

**Comment by gmatsuoka** [comment]
O pagamento que você criou foi utilizando a API /v1/payments, nela não é criado uma merchant_order. 

Apenas na API /checkout/preferences é criado esse objeto, logo, pagamentos criados a partir desse checkout irá ter essa informação.
