### ISSUE TITLE
Erro crítico - Boleto

### ISSUE THREAD

**Issue by davirs** [mercadopago/cart-magento#262]
Notei minhas vendas extremamente abaixo do normal, fui até o checkout conferir e olha que bizarrice começou acontecer:
![image](https://user-images.githubusercontent.com/4355062/41256901-6180341e-6da1-11e8-94a7-3739e2b5ceb9.png)

![image](https://user-images.githubusercontent.com/4355062/41256951-98404804-6da1-11e8-9d17-da01fe68db72.png)

![image](https://user-images.githubusercontent.com/4355062/41256816-259a101e-6da1-11e8-8c78-9f2a131fd3a5.png)

Houve alguma mudança no mercado pago?

**Comment by pfgianoto** [comment]
Também identifiquei isso em uma loja de cliente. Não sei da onde saiu isso! Vou tentar remover com CSS.

**Comment by davirs** [comment]
@pfgianoto E ai beleza? Ta largadaço o módulo do mercado pago. Até hoje não funciona compra com 2 cartões e tem muito layout quebrado... pro tamanho da empresa é uma vergonha!!!!

O que acontece é o seguinte, o MP simplesmente criou um serviço "pagamento na lotéricas" escrito assim ainda por cima... quando o cliente escolhe isso ele sai da loja, entra no MP e pode localizar a lotérica mais próxima... a ideia é boa mas na prática duvido que pegue.. é chato e a grande maioria do cliente é leigo. O simples fato de sair da loja já não ajuda.

![image](https://user-images.githubusercontent.com/4355062/41310769-dbe778d6-6e58-11e8-9c12-f0a5c832d47d.png)


Isso aparece junto com o boleto. Todo mundo que tem versão antiga do módulo isso ai vai aparecer direto pela API sem nenhuma opção para remover.

Se instalar a última versão do módulo lá no painel da pra escolher somente o boleto e desabilitar essa opção nova.

Eu estava com medo de instalar o porque a última vez tive que dar rollback no módulo, mas os testes até agora estão OK

Eu fico indignado que função que presta e que realmente efetiva vendas, como é o caso do pagamento com 2 cartões não funciona... Já mostrar lotérica no mapa que é totalmente descartável perdem o tempo fazendo... Vai entender!

**Comment by pfgianoto** [comment]
Pois é! Fiquei sabendo hoje por que um cliente me perguntou o que era. Eu nem estava sabendo. Também não gosto de ficar atualizando módulo toda hora, tirei no CSS mesmo:

ul li.mercadopago-ticket-option:first-child {
    display: none;
}

O Ruim é que o cliente tem que seleciona boleto bancario e depois clicar em boleto bancario de novo. Se eu bolar algo compartilho aqui com voce.

**Comment by gmatsuoka** [comment]
O módulo mais atual já possui a funcionalidade de não aceitar um método de pagamento "Ticket", com isso é possível desabilitar o método de pagamento PEC, até que seja corrigido a questão da imagem.

**Comment by davirs** [comment]
@gmatsuoka Se atualizar para o módulo atual paro de vender. Simplesmente da pau com o método de frete, quando seleciona algum envio trava o pagamento.

Continuo sem auxílio.
