### ISSUE TITLE
Error al enviar a Mercado Pago cuando el total a pagar es cero pero se envía por Mercado Envíos

### ISSUE THREAD

**Issue by nmarquev** [mercadopago/cart-magento#266]
Si el pedido tiene total a pagar cero, porque tiene un descuento del 100% sobre los productos, pero el cliente selecciona Mercado Envío, el módulo tiene un bug que el llamar a MP este verifica que el total a pagar es cero y devuelve el error:

{"status":400,"response":{"message":"unit_price invalid","error":"invalid_items","status":400,"cause":[]}}

Esto es porque como el costo de Mercado Envío lo vuelve a calcular dentro de MP, no se lo manda y por eso interpreta que no debe pagar nada. 

En el caso que Mercado Envío, debería permitir igual ir a MP

Saludos

**Comment by gmatsuoka** [comment]
El módulo no tiene la funcionalidad de procesar pagos "Zerados" y también existe una regla en el Mercado Envíos que la somatoria del valor de los productos tiene que ser superior al valor cobrado por el Mercado Envios.
