### ISSUE TITLE
error de "Invalid installments" al pagar 

### ISSUE THREAD

**Issue by LismarYaquer** [mercadopago/cart-magento#269]
al momento de intentar pagar con tarjeta de credito en magento 1, me exige como obligatorio las cuotas, pero en venezuela creo que no es obligatorio y solo me aparece la opcion "Elegir" al intentar hacer el pago me dice "Invalid installments"
![selection_007](https://user-images.githubusercontent.com/12056813/43724426-ee1895f0-9967-11e8-89d0-378b48af332d.png)
![menu_008](https://user-images.githubusercontent.com/12056813/43343149-2b71d040-91b3-11e8-876e-8060f5c57606.png)
![selection_009](https://user-images.githubusercontent.com/12056813/43343148-2b5522d8-91b3-11e8-9360-1c9a0b7e0439.png)

**Comment by LismarYaquer** [comment]
Aun sigo a la espera de su respuesta a este inconveniente

**Comment by barbazul** [comment]
Vas a esperar un largo tiempo a que te den una respuesta oficial de MP por este canal, lamentablemente 👎 .

Alguna vez investigué ese código. El formulario "transparent" se genera en base a un JS que, a medida que vas completando los campos, obtiene la lista de los planes de cuotas mediante la API de MP.

Es posible que, si en Venezuela las cuotas no son obligatorias, desde el servidor la respuesta no incluya cuotas y ese sea un caso no contemplado en el JS. Podrías validar en la consola del navegador cual es la repsuesta obtenida del AJAX.

Un par de cosas que investigaría en tu lugar:

1. Revisa si el módulo está configurado en modo "Gateway" y también si corresponde o no que este en ese modo de acuerdo a tu acuerdo comercial con MP
2. Modifica el JS para que en el caso que la respuesta de la API no devuelva planes de cuotas, igualmente agregue en el dropdown la opción "1 cuota". Sospecho que enviar 1 cuota cuando no manejas cuotas debería resolver tu inconveniente.

**Comment by barbazul** [comment]
**Importante** Remueve la captura de pantalla del posteo original si esa información corresponde a una tarjeta de crédito real.

**Comment by gmatsuoka** [comment]
@LismarYaquer, Actualmente el módulo quita el campo de parcelas cuando se identifica la tarjeta, para que el módulo debe estar configurado correctamente.

Sigue algunos ejemplos de pantalla de ejemplo:

1) País configurado en el módulo:
![captura de tela 2018-08-07 as 13 47 15](https://user-images.githubusercontent.com/1392359/43790268-798a3a86-9a48-11e8-8cd8-a820519c146a.png)

2) Formulario es inicializado:
![captura de tela 2018-08-07 as 13 46 29](https://user-images.githubusercontent.com/1392359/43790264-7850669a-9a48-11e8-9542-8f7cbb1e3ed5.png)

3) Tarjeta es identificada y el campo de parcelas es quitado:
![captura de tela 2018-08-07 as 13 46 39](https://user-images.githubusercontent.com/1392359/43790266-78bc8988-9a48-11e8-9eb1-8fa790ce58f7.png)

4) Pago finalizado:
![captura de tela 2018-08-07 as 13 49 51](https://user-images.githubusercontent.com/1392359/43790373-cd80fa76-9a48-11e8-8e0a-499a3e0d5fb7.png)
