### ISSUE TITLE
cart-magento break my template

### ISSUE THREAD

**Issue by rubenosvaldorodriguez** [mercadopago/cart-magento#28]
Hello.

I have a problem and would like to ask your help please.

In my server install a 'MAGENTO' with a TEMPLATE 'TEMPLATE MONSTER'.

Everything okay up there ... but:

When installing 'CART-MAGENTO' on my site stop working several things. No language works, or the scroll of the shopping cart, or handling some images.

QUESTION:

What do you recommend me to do? Where can be the problem? How do I prevent the 'cart-magento' break the template?

I await your kind response.

Thank you.

mi mail: rubenosvaldorodriguez(arroba)gmail.com

**Comment by esavignone** [comment]
Hi @rubenosvaldorodriguez ,

Ticket will be closed, please reopen if the issue persists.

Best,
