### ISSUE TITLE
Sku con guiones

### ISSUE THREAD

**Issue by joaquinbecerra** [mercadopago/cart-magento#31]
Tengo productos cuyo sku contiene guiones, por ejemplo:

'sapatilla-talle-45'

El problema surge en el archivo:

https://github.com/mercadopago/cart-magento/tree/master/v1.6.x - 1.7.x/app/code/community/Mpexpress/Model/Express.php

linea 59:

         //modificado por e-values para permitir el manejo de kits
            if (strpos($item->getSku(), '-') !== false) {
                $skus = explode("-", $item->getSku());
                $prod = $model->loadByAttribute('sku', $skus[0]);
            } else {
                $prod = $model->loadByAttribute('sku', $item->getSku());
            }

En este caso trata de cargar el producto con sku 'zapatilla', que no existe y termina la ejecucion con un error.

Por otro lado:

No entiendo por que agregaron este código:
 $methods = get_class_methods($prod);
            foreach($methods as $method):
                if($method == "getImageUrl"):
                    $image[] = $prod->getImageUrl();
                endif;
            endforeach;

Seria mas prolijo llamar directamente a $prod->getImageUrl(); y evaluar la respuesta.

Saludos

**Comment by ekupelian** [comment]
El pull request #60 resolvería este issue

**Comment by barbazul** [comment]
Muchachos, saquen toda la logica de ese load y usen directamente la info del item.

O, si igual quieren meter el load adentro del foreach, hagan un load por product_id. La logica que usan para el load por SKU sencillamente sobra.
