### ISSUE TITLE
El status de la orden no se actualiza correctamente

### ISSUE THREAD

**Issue by juanhuerta** [mercadopago/cart-magento#33]
Tengo Magento 1.7.0.2, instalé el módulo de Mercadopago, ya hice pruebas con todos los medios (pago en tienda, en banco, tarjeta de crédito, tarjeta de débito), y si se hace el proceso con el IPN y Mercadopago si actualiza el estado a Processing, pero al revisar la orden, en la sección de comentarios sólo esta la opción de "Pending" en el dropdown.

Incluso las ordenes se facturan correctamente, pero si necesitamos poder cambiar el orden de Processing a un estado custom que nosotros usamos dentro del grupo de Processing. ¿Alguna Ayuda?

![captura](https://cloud.githubusercontent.com/assets/7265780/2682554/d4f61fa4-c19c-11e3-996f-abbbe6c30bfc.JPG)

**Comment by esavignone** [comment]
Hola @juanhuerta ,

Pudiste resolver el problema?

Saludos,

**Comment by juanhuerta** [comment]
Hola. Eso fue hace más de dos años y sinceramente ya no recuerdo cómo se
solucionó.

Saludos

**Comment by esavignone** [comment]
Gracias por la respuesta @juanhuerta, supusimos que estaría solucionado, estamos limpiando la queue de Github y no queríamos cerrarlo sin antes corroborarlo.

Saludos,
