### ISSUE TITLE
Problema json o similar

### ISSUE THREAD

**Issue by estudioloop** [mercadopago/cart-magento#35]
![captura](https://cloud.githubusercontent.com/assets/1449243/2921776/4a5be2ae-d6f8-11e3-9cb6-cf8d739469c0.PNG)
Estuve revisando las issues de otros usuarios, pero ninguna solucionó nuestro problema, nos devuelve el siguiente error de magento al pasar al checkout:

a:5:{i:0;s:111:"No such property: cost for class: org.codehaus.groovy.grails.web.json.JSONObject$Null
Possible solutions: class";i:1;s:2959:"#0 /home/click/public_html/lib/mercadopago/mercadopago.php(306): MPRestClient::exec('POST', '/checkout/prefe...', Array, 'application/jso...')
#1 /home/click/public_html/lib/mercadopago/mercadopago.php(157): MPRestClient::post('/checkout/prefe...', Array)

Ni siquiera muestra el error en el debug, tira error de magento directamente. En el servidor anterior funciona correctamente, pero no encontramos diferencias de configuración, alguna sugerencia de que podría ser?

Adjunto captura.

php 5.4.28
myql 5.5.36
apache 2.2.27

**Comment by esavignone** [comment]
Hola @estudioloop ,

Seguis teniendo el problema?

Saludos,

**Comment by estudioloop** [comment]
Hola, el post es demasiado viejo, no ocurre con las ultimas versiones de
mercadopago.



2016-06-13 8:44 GMT-03:00 Esteban Savignone <notifications@github.com>:

**Comment by esavignone** [comment]
Gracias por la respuesta @estudioloop.

Saludos,
