### ISSUE TITLE
Versión beta - no toma cupones de descuento

### ISSUE THREAD

**Issue by juansss** [mercadopago/cart-magento#44]
Hola, hoy subieron un pull-request mio ya que la beta no tomaba el precio especial del producto.

Veo también que el checkout no está tomando los cupones de descuento que pudo haber agregado el usuario. Pero no logro obtener el cupon de descuento ingresado en su archivo model/Checkout.php para poder aplicarselo al final price del producto...

Me dan una mano?

**Comment by DiegoRodriguezTandil** [comment]
He encontrado que el error se produce cuando el producto se encuentra en Sale, los cupones de descuento no son aplicados, alguna ayuda?

**Comment by esavignone** [comment]
Hola @juansss ,

El ticket será cerrado, por favor reabrir si el problema persiste.

Muchas gracias!
