### ISSUE TITLE
Integracion con Magento 1.9.0.1

### ISSUE THREAD

**Issue by aodreman** [mercadopago/cart-magento#46]
Saludos, 

Estoy tratando de integrar este modulo con una tienda en Magento 1.9.0.1 que ya tenemos desarrollada pero luego de que el modulo solicita el código postal del cliente, Magento reporta un error, anexo el trace del error al final de este post.

Lo único que debí modificar para que el modulo funcionara fue la librería de jQuery ya que la incluida en el modulo (1.7) estaba rompiendo uno de los sliders, por lo tanto la reemplace por la siguiente:
jquery-migrate-1.2.1.js

Agradezco cualquier ayuda para identificar que pude estar pasando con este modulo ya que es la primera integración que hago de Magento con Mercado Pago.

Gracias.

El trace del error es el siguiente:
a:5:{i:0;s:12:"items needed";i:1;s:2160:"#0 /Users/aodreman/Developer/Websites/alelimon/lib/mercadopago/mercadopago.php(306): MPRestClient::exec('POST', '/checkout/prefe...', Array, 'application/jso...')
#1 /Users/aodreman/Developer/Websites/alelimon/lib/mercadopago/mercadopago.php(157): MPRestClient::post('/checkout/prefe...', Array)
#2 /Users/aodreman/Developer/Websites/alelimon/app/code/community/Mpexpress/Model/Checkout.php(29): MP->create_preference(Array)
#3 /Users/aodreman/Developer/Websites/alelimon/app/code/community/Mpexpress/Block/Checkout/Cart.php(119): Mpexpress_Model_Checkout->GetCheckout(Array, '')
#4 /Users/aodreman/Developer/Websites/alelimon/app/code/community/Mpexpress/Block/Checkout/Cart.php(31): MPexpress_Block_Checkout_Cart->setMpCart()
#5 /Users/aodreman/Developer/Websites/alelimon/app/code/core/Mage/Core/Block/Abstract.php(918): MPexpress_Block_Checkout_Cart->_beforeToHtml()
#6 /Users/aodreman/Developer/Websites/alelimon/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#7 /Users/aodreman/Developer/Websites/alelimon/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#8 /Users/aodreman/Developer/Websites/alelimon/app/code/community/Mpexpress/controllers/CheckoutController.php(72): Mage_Core_Controller_Varien_Action->renderLayout()
#9 /Users/aodreman/Developer/Websites/alelimon/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mpexpress_CheckoutController->cartAction()
#10 /Users/aodreman/Developer/Websites/alelimon/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('cart')
#11 /Users/aodreman/Developer/Websites/alelimon/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /Users/aodreman/Developer/Websites/alelimon/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /Users/aodreman/Developer/Websites/alelimon/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /Users/aodreman/Developer/Websites/alelimon/index.php(87): Mage::run('', 'store')
#15 {main}";s:3:"url";s:35:"/index.php/mpexpress/checkout/cart/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}

**Comment by esavignone** [comment]
Hola @aodreman ,

El ticket será cerrado, por favor reabrir si el problema persiste.

Muchas gracias!
