### ISSUE TITLE
Error ao finalizar pedido No magento

### ISSUE THREAD

**Issue by ronaldopadula** [mercadopago/cart-magento#49]
Ao finalizar o pedido dá o seguinte erro:

There has been an error processing your request

cannot exclude all payments methods

Trace:
#0 /home/camaleonicos/public_html/lib/mercadopago/mercadopago.php(306): MPRestClient::exec('POST', '/checkout/prefe...', Array, 'application/jso...')
#1 /home/camaleonicos/public_html/lib/mercadopago/mercadopago.php(157): MPRestClient::post('/checkout/prefe...', Array)
#2 /home/camaleonicos/public_html/app/code/community/Mpexpress/Model/Checkout.php(29): MP->create_preference(Array)
#3 /home/camaleonicos/public_html/app/code/community/Mpexpress/Model/Express.php(196): Mpexpress_Model_Checkout->GetCheckout(Array, false)
#4 /home/camaleonicos/public_html/app/code/community/Mpexpress/Block/Checkout/Redirect.php(19): Mpexpress_Model_Express->getInitPoint()
#5 /home/camaleonicos/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mpexpress_Block_Checkout_Redirect->_toHtml()
#6 /home/camaleonicos/public_html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#7 /home/camaleonicos/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#8 /home/camaleonicos/public_html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#9 /home/camaleonicos/public_html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#10 /home/camaleonicos/public_html/app/design/frontend/fortis/default/template/page/3columns.phtml(61): Mage_Core_Block_Abstract->getChildHtml('content')
#11 /home/camaleonicos/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/camaleoni...')
#12 /home/camaleonicos/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/fortis...')
#13 /home/camaleonicos/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#14 /home/camaleonicos/public_html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#15 /home/camaleonicos/public_html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#16 /home/camaleonicos/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#17 /home/camaleonicos/public_html/app/code/community/Mpexpress/controllers/CheckoutController.php(237): Mage_Core_Controller_Varien_Action->renderLayout()
#18 /home/camaleonicos/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mpexpress_CheckoutController->redirectAction()
#19 /home/camaleonicos/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('redirect')
#20 /home/camaleonicos/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#21 /home/camaleonicos/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#22 /home/camaleonicos/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#23 /home/camaleonicos/public_html/index.php(87): Mage::run('', 'store')
#24 {main}

**Comment by matiasgordon** [comment]
Olá Ronaldo, 

Selecione os meios de pagamento oferecidos pelo MercadoPago que você NÃO deseja aceitar em System > Configuration > Sales > Payment Methods > MercadoPago. 

Você não pode selecionar todos!

Atenciosamente,
Matías Gordon | IT Analyst MercadoPago
