### ISSUE TITLE
Items Needed

### ISSUE THREAD

**Issue by goodworkslat** [mercadopago/cart-magento#50]
Hola, tengo un problema con el express checkout en magento v1.9.1:
Al hacer click en el boton "comprar ahora" me aparece para ingresar el codigo postal, luego selecciono el costo de envio y en el paso siguiente me sale el error:

items needed

Trace:
#0 /home4/goodw/public_html/ecommerce/lib/mercadopago/mercadopago.php(306): MPRestClient::exec('POST', '/checkout/prefe...', Array, 'application/jso...')
#1 /home4/goodw/public_html/ecommerce/lib/mercadopago/mercadopago.php(157): MPRestClient::post('/checkout/prefe...', Array)
#2 /home4/goodw/public_html/ecommerce/app/code/community/Mpexpress/Model/Checkout.php(29): MP->create_preference(Array)
#3 /home4/goodw/public_html/ecommerce/app/code/community/Mpexpress/Block/Checkout/Cart.php(119): Mpexpress_Model_Checkout->GetCheckout(Array, 'bapropagos')
#4 /home4/goodw/public_html/ecommerce/app/code/community/Mpexpress/Block/Checkout/Cart.php(31): MPexpress_Block_Checkout_Cart->setMpCart()
#5 /home4/goodw/public_html/ecommerce/app/code/core/Mage/Core/Block/Abstract.php(918): MPexpress_Block_Checkout_Cart->_beforeToHtml()
#6 /home4/goodw/public_html/ecommerce/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#7 /home4/goodw/public_html/ecommerce/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#8 /home4/goodw/public_html/ecommerce/app/code/community/Mpexpress/controllers/CheckoutController.php(72): Mage_Core_Controller_Varien_Action->renderLayout()
#9 /home4/goodw/public_html/ecommerce/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mpexpress_CheckoutController->cartAction()
#10 /home4/goodw/public_html/ecommerce/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('cart')
#11 /home4/goodw/public_html/ecommerce/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /home4/goodw/public_html/ecommerce/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /home4/goodw/public_html/ecommerce/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /home4/goodw/public_html/ecommerce/index.php(87): Mage::run('', 'store')
#15 {main}

Alguna idea?
gracias

**Comment by cyberiano** [comment]
@goodworkslat Lo pudiste resolver?

Estoy con el mismo problema....

**Comment by esavignone** [comment]
Please, reopen if the issue continues.

Thanks!
