### ISSUE TITLE
Preço das parcelas formatação de preço

### ISSUE THREAD

**Issue by guztavoalves** [mercadopago/cart-magento#52]
Olá,

gostaria de mudar o padrão de formatação do preço das parcelas exibidas no campo Parcelas*
http://prntscr.com/675z0q

Gostaria de mudar o padrão para 
1x de R$ 130,00
2x de R$ 65,00
...etc

Como posso alterar?

**Comment by esavignone** [comment]
Oi @guztavoalves ,

O ticket será fechado, por favor reabrir se o problema persistir.

Obrigado,
