### ISSUE TITLE
Conflitos arquivos .js

### ISSUE THREAD

**Issue by guztavoalves** [mercadopago/cart-magento#55]
Estou com um problema de conflito no jquery do tema da minha loja com o do Módulo do Mercadopago

Vi que o arquivo /js/mercadopago/mercadopago.js carrega externamente o arquivo
//code.jquery.com/jquery-1.11.0.min.js e acredito que seja esse o causador do problema...

É possivel remover esse load sem prejudicar o funcionamento do módulo, já que o tema da minha loja já possui jquery incluso?

Endereço da loja
http://www.dressus.com.br/

Obrigado

**Comment by willianclf** [comment]
guztavoalves,

Você poderia me informar como vc resolveu ? pois estou com o mesmo problema! obrigado!

**Comment by guztavoalves** [comment]
willianclf,
não consegui resolver, a solução foi abandona o OSC até que resolvam esse problema do módulo.

Se encontrar alguma solução, posta aqui. ;)

**Comment by esavignone** [comment]
Oi @guztavoalves ,

O que OSC está usando?

Obrigado,

**Comment by esavignone** [comment]
Oi @guztavoalves,

Você ainda tem o problema?

Obrigado,

**Comment by esavignone** [comment]
Oi @guztavoalves ,

O ticket será fechado, por favor reabrir se o problema persistir.

Obrigado,
