### ISSUE TITLE
Modulo CC Transparent

### ISSUE THREAD

**Issue by altpc** [mercadopago/cart-magento#64]
Estou tendo problemas quando tento concluir a compra utilizando o módulo transparente do MercadoPago. 

A validação do número de cartão, mes e ano de validade, sempre está retornando que estes campos são inválidos.

Alguem teve o mesmo problema? Alguma solução?

**Comment by esavignone** [comment]
Oi @altpc ,

Você ainda tem o problema?

Obrigado,

**Comment by esavignone** [comment]
Oi @altpc ,

O ticket será fechado, por favor reabrir se o problema persistir.

Obrigado,
