### ISSUE TITLE
2 Credit Cards support

### ISSUE THREAD

**Issue by barbazul** [mercadopago/cart-magento#68]
MercadoPago recently started accepting 2 payments with 2 credit cards. According to your comunication on the subject, existing integrations would break if not updated.

I have disabled the 2 CC payment option on every installation I run and I have not experienced any issues so far, but I am affraid if I enable the option, the IPN will break as I don't see any commit in the log related to this issue and looking at the current state of the Notifications controller, it does not match the suggested logic for multiple payments from this example https://github.com/mercadopago/sdk-php/blob/master/examples/instant-payment-notifications/receive-ipn.php

What is the status of 2 credit cards support in for this module?

**Comment by barbanet** [comment]
@barbazul did you've received any information about this issue?

**Comment by barbazul** [comment]
Nope. Nothing so far

**Comment by esavignone** [comment]
Hi @barbazul ,

Do you still have this issue?

Best,

**Comment by barbazul** [comment]
Nunca usé este feature porque no se presentó la necesidad y porque cuando
lo revisé, no estaba soportado por el módulo.

No sé si ya le agregaron soporte o no. Vos me dirás.

**Comment by esavignone** [comment]
Hola @barbazul ,

El módulo soporta la funcionalidad, por el momento solo está presente solo para el checkout clásico.

Saludos,
