### ISSUE TITLE
Mercado Pago Transparent Model

### ISSUE THREAD

**Issue by DiegoRodriguezTandil** [mercadopago/cart-magento#70]
In the Mercadopago/Transparent/Model/Transparent class is using a htmlEscape method and it is not present in the class. 

The saveOrderAction in OnePageController trigger an Exception with the following message: "Invalid method MercadoPago_Transparent_Model_Transparent::htmlEscape(Array (     [0] => {"code":0,"description":"Unknown error"} ) )"

**Comment by fcapua-summa** [comment]
Hello @DiegoRodriguezTandil 

I invite you to download the latest version of the plugin here: https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x

If the problem persists please feel free to create a new issue.

Thanks!
