### ISSUE TITLE
Módulo não fecha pedidos.

### ISSUE THREAD

**Issue by pelligotti** [mercadopago/cart-magento#74]
nada ocorre ao clicar em "Fechar pedido".
Notei o seguinte erro no console:
uncaught referenceerror review is not defined

**Comment by fcapua-summa** [comment]
Dado o momento da criação desse problema e falta de atualização Fechei o problema.

Se você tiver dúvidas ou problemas, por favor, crie uma nova questão para que possamos ajudá-lo.

Thanks!
