### ISSUE TITLE
Conflito no JS

### ISSUE THREAD

**Issue by pelligotti** [mercadopago/cart-magento#76]
Boa tarde, 
o módulo está entrando em conflito e impedindo o funcionamento de outro código..
alguém sabe como posso resolver esse problema?

**Comment by barbanet** [comment]
I guess that you're using Magento 1.9.x version and the RWD theme or at least you're using the jQuery library.
There's a conflict there because the MercadoPago module includes another copy of Jquery. You'll need to customize which one jQuery library you'll include.

**Comment by fcapua-summa** [comment]
Dado o momento da criação desse problema e falta de atualização Fechei o problema.

Se você tiver dúvidas ou problemas, por favor, crie uma nova questão para que possamos ajudá-lo.

Thanks!
