### ISSUE TITLE
IPN url en ultima version del modulo

### ISSUE THREAD

**Issue by roberfizzmod** [mercadopago/cart-magento#82]
Desde que actualice a la ultima versión de este modulo, la url de IPN no funciona mas. 

Antes era: mysite/mpexpress/ipn

Necesito por favor la url que funciona ahora.

**Comment by barbanet** [comment]
Si estás usando la versión nueva disponible en Github, mirá en https://github.com/mercadopago/cart-magento/blob/master/v1.6.x%20-%201.9.x%20-%20Transparent/app/code/community/MercadoPago/controllers/NotificationsController.php

**Comment by barbanet** [comment]
Fijate que cambiaron la definición del router en la versión: https://github.com/mercadopago/cart-magento/blob/master/v1.6.x%20-%201.9.x%20-%20Transparent/app/code/community/MercadoPago/etc/config.xml#L80

**Comment by sheikgit** [comment]
Hola,
No la tengo muy clara con el framewor de magento todavía, por lo que sigo sin enteder... cómo sería, concretamente, la nueva URL?

**Comment by mroffe** [comment]
Hola sheikgit, ya no necesitas configurar ninguna url, lo hace solo.

**Comment by sheikgit** [comment]
Gracias por la pronta respuesta!!! Qué nivel!! :)

¿Pero MercadoPago sabe "solo" a qué URL enviar notificaciones? ¿Acaso
cuando Magento envía la info a MP para procesar la compra le envía la URL
de notificaciones? Yo por las dudas en MP puse
http://misitio.com.ar/mercadopago/notifications y todo parece funcionar
correctamente (usé tarjetas y usuario comprador y vendedor de prueba).

*IMPORTANTE*:  Al menos con los usuarios de prueba (vendedor y comprador)
Estoy recibiendo dos notificaciones de MP a Magento (en la URL de
notificacione), una con el importe del ítem comprado, y otra con un importe
$0 (cero pesos). No sé si corresponderá a que el método de envío  de
Magento es gratuito y MP está mandando una factura de $0 por el envío,
separada de la del artículo vendido. Esto aparentemente es lo que me está
generando dentro de Magento la generación de dos facturas (invoices) para
la misma orden (una con el importe real y otra con $0) y el correspondiente
envío de dos mails al cliente, uno por cada factura. Otra cosa rara es que
en el mail de la factura de $0, figura el mismo importe de IVA (unos $2000)
que en la FC del artículo, pero un importe total de $0, mientras que en
Magento, esta FC de $0  figura todo en $0, sin IVA, y con la lista de ítems
facturados vacía (la FC del artículo parece estar bien)


Alguna idea de lo que puede estar pasando? Será el ambiente de prueba de MP
que anda mal?

Saludos y gracias!!

**Comment by fcapua-summa** [comment]
Hola @sheikgit,

Te sugiero que actualices el plugin a la última versión del plugin que puedes descargar aquí: https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x

Y nos digas si sigues con problemas.

Saludos!

**Comment by dsueiro** [comment]
Con la última versión, utilizando Standard Checkout Payment y usuarios de test, los mensajes que recibimos del IPN son sólo con topic _payment_ pero el módulo parece estar esperando mensajes con topic _merchant_order_.

**Comment by NICOCACHA** [comment]
Hola. Tengo un problema con la integración transparente de Mercadopago, queria ver si me podian ayudar. Es bien simple y no veo una posible explicación, las IPN no llegan al URL configurado en mi cuenta mercadopado.
El link que suministro es: http://www.mipagina.tv/modulo/notify/index.php
y luego de efectuar una venta, el servidor de mercadopago me envia la IPN de la siguiente manera:
http://www.mipagina.tv/?preapproval_id=99dc15758e8449928884837e07d5d39b

O sea, al root de mi pagina y no a la URL que configure.
Me podrian orientar para ver cual es la posible solución?
Muchas gracias !

**Comment by imasson** [comment]
Hola @NICOCACHA , seuis con el mismo problema?
Podrias adjuntar los logs de mercadopago para tratar de detectar el error?

Saludos!

**Comment by NICOCACHA** [comment]
Hola @imasson ! Solucionado, no fue fácil. Básicamente falta de documentación de parte del proveedor. No pusimos en contacto con un Ing. de Mercadopago y con su ayuda se resolvió.
Abrazo y gracias!

**Comment by imasson** [comment]
Excelente @NICOCACHA !
Me podrias decir cual era la solucion para saber en caso de que ocurra nuevamente?
