### ISSUE TITLE
Dados incorretos, valide os dados. Por favor.

### ISSUE THREAD

**Issue by roneclay** [mercadopago/cart-magento#84]
Pelo amor de Deus nos ajudem!
Estamos perdendo muito dinheiro por causa das falhas deste módulo.
Sabemos que é grtauito, mas funcionar deveria ser o mínimo.

Estamos com problemas com pagamento via cartão de crédito. Antes de atualizarmos para a última versão hoje, as parcelas não atualizavam com os valores corretos caso houvesse regra de desconto para outro método de pagamento, como boleto por exemplo.

Hoje atualizamos e a falha acima sumiu, como num passe de mágica, mas agora o problema é outro. Já usamos dezenas de cartão de créditos de várias bandeiras e sempre recebemos o erro: "Dados incorretos, valide os dados. Por favor."

Existe alguma forma deste módulo funcionar corretamente? Estávamos pensando em contribuir com o autor do mesmo, mas infelizmente estamos impossibilitados.

Agradecemos a compreensão ao nosso desespero.

Se alguém puder dar uma luz, agradecemos.

**Comment by gmatsuoka** [comment]
Olá rone, tudo bem?

Pode me passar a url do seu site para eu efetuar alguns testes e identificar o problema?

Atenciosamente,

Gabriel.

**Comment by roneclay** [comment]
Olá @gmatsuoka, meu diretor de operações pediu que eu voltasse a versão anterior do módulo, já que ninguém consegue comprar por conta do erro: "Dados incorretos, valide os dados. Por favor."

No momento, está com o erro que não atualiza o valor das parcelas. Com boleto os clientes tem desconto, mas no cartão o desconto do boleto está permanecendo.

A loja é http://territorioonline.com.br/ ver se consegue dá uma olhadinha por gentileza.

Grato, pelo retorno.

**Comment by gmatsuoka** [comment]
Olá @roneclay,

Esse erro já aconteceu com outros vendedores, semelhante ao seu caso: depois de atualizar o Módulo para o mais atual.

Foi necessário limpar o cache do Magento (css & javascript) e do navegador para resolver esse problema. Se possível me adicione no skype gmatsuoka1, assim podemos fazer testes realtime e identificar se esse problema é resolvido com esses procedimentos.

Atenciosamente,

Gabriel

**Comment by rafaelobo** [comment]
Alguma solução para isso? Estou com o mesmo problema. @roneclay , qual a sua versão estável?

**Comment by roneclay** [comment]
@rafaelobo versão 2.0.0

**Comment by roneclay** [comment]
@gmatsuoka,

Mesmo problema com outro cliente.
Acabamos de instalar o módulo local e em homolog..limpamos todos os caches possíveis e reindexamos tudo, mas a mensagem "Dados incorretos, valide os dados. Por favor." não sai de forma alguma.

```
<p class="msg-status error-other validation-advice" style="display: block;">Dados incorretos, valide os dados. Por favor.</p>

```

**Comment by roneclay** [comment]
Após uma longa jornada acabei descobrindo que o problema era mais simples do que eu pensava.
O módulo está adicionando, obrigatoriamente, mais uma versão do jQuery ao checkout e com isso há, sem dúvidas, conflito entre as versões.

Na verdade, quando eu desabilitada o OSC6 funcionava de boa, mas bastava habilitar e o problema voltava.

Foi difícil encontrar essa nova instância por que ela é feita via JavaScript e não via xml, sendo impossível verificar pelo código fonte da página; somente percebi após inspecionar o elemento <head> pelo firebug.

Se alguém ainda estiver com esta dificuldade, segue a forma que tive que fazer para funcionar:

>> No arquivo ../js/mercadopago/mercadopago.js, na linha 19 há a função: loadJsAsync.

Era assim:

```
loadJsAsync("//code.jquery.com/jquery-1.11.0.min.js", function () {
    showLogMercadoPago("jQuery Running ...");
    $.noConflict();
    
    loadJsAsync("https://secure.mlstatic.com/org-img/checkout/custom/1.0/checkout.js?nocache=" + Math.random() * 10, function () {
            showLogMercadoPago("MercadoPago Running ...");
            Checkout.setPublishableKey(PublicKeyMercadoPagoTransparent);
        
    });//end load mp
    
});//end load js
```
E eu deixei assim:

```
/*loadJsAsync("//code.jquery.com/jquery-1.11.0.min.js", function () {
    showLogMercadoPago("jQuery Running ...");*/
    $.noConflict();

    loadJsAsync("https://secure.mlstatic.com/org-img/checkout/custom/1.0/checkout.js?nocache=" + Math.random() * 10, function () {
            showLogMercadoPago("MercadoPago Running ...");
            Checkout.setPublishableKey(PublicKeyMercadoPagoTransparent);

    });//end load mp

/*});//end load js*/
```

**Comment by lmarquine** [comment]
Senhores, essa solução funcionou para todos? Comigo não deu certo, o símbolo de loading aparece infinitamente.

**Comment by lmarquine** [comment]
Senhores, mais um problema rs, havia me livrado disso e agora voltou. O que pode ser? Já tentei mexer em todos os tokens.

![captura de tela 2015-10-22 as 22 21 04](https://cloud.githubusercontent.com/assets/8151683/10681729/599b9f14-790b-11e5-869d-2f0e6b870c24.png)

**Comment by fcapua-summa** [comment]
Dado o momento da criação desse problema e falta de atualização Fechei o problema.

Se você tiver dúvidas ou problemas, por favor, crie uma nova questão para que possamos ajudá-lo.

Thanks!
