### ISSUE TITLE
MercadoPago Custom

### ISSUE THREAD

**Issue by lee-xu** [mercadopago/cart-magento#85]
Cuando intento realizar un pago utilizando el método de pago "MercadoPago Custom - Tickets de pago" o "MercadoPago Custom - Tarjeta de Crédito", se genera el siguiente error:

No pudimos procesar tu pago. {"status":401,"response":{"message":"access denied","error":"unauthorized","status":401,"cause":{"code":"300","description":"This app cannot do custom payments"}}}No pudimos procesar tu pago. {"status":401,"response":{"message":"access denied","error":"unauthorized","status":401,"cause":{"code":"300","description":"This app cannot do custom payments"}}}

**Comment by sebagun** [comment]
@lee-xu Dirigite a https://www.mercadopago.com/mla/account/credentials y completá el formulario para solicitar operar en modo producción. Luego de eso vas a poder recibir pagos.
Saludos

**Comment by lee-xu** [comment]
Muchas gracias, me veo en la específica.
