### ISSUE TITLE
¿Cómo establecer el pago a plazos en nuestro sitio?

### ISSUE THREAD

**Issue by lee-xu** [mercadopago/cart-magento#86]
Estamos construyendo un sitio web para compras en línea, que se basa en el sistema operativo Magento (feriaandes.com.ar). Ahora hemos integrado el sitio con MercadoPago. ¿Cómo establecer el pago a plazos en nuestro sitio?

¡Muchas gracias!

**Comment by fcapua-summa** [comment]
Dado el tiempo de creación de este issue y falta de actualización doy por cerrado el problema.

Si tiene alguna duda o problema, por favor cree un nuevo issue para que podamos atenderlo.

Gracias!
