### ISSUE TITLE
Validação 2x do CPF

### ISSUE THREAD

**Issue by magnored** [mercadopago/cart-magento#87]
Gostaria de saber se é possivel permitir que o cliente digite o CPF apenas uma vez para validar 
Pois o magento ja possui o campo VAT para isso e quando é selecionado a forma de pagamento via cartao (transparente) ele pede denovo

**Comment by fcapua-summa** [comment]
Dado el tiempo de creación de este issue y falta de actualización doy por cerrado el problema.

Si tiene alguna duda o problema, por favor cree un nuevo issue para que podamos atenderlo.

Gracias!
