### ISSUE TITLE
NO FUNCIONA EL MODULO DE MAGENTO

### ISSUE THREAD

**Issue by jesskams** [mercadopago/cart-magento#88]
Hola tengo este problema!! que tengo que hacer???

a:5:{i:0;s:146:"SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed";i:1;s:2075:"#0 /www/promocionesmovistar/htdocs/lib/mercadopago/mercadopago.php(439): MPRestClient::exec('GET', '/item_categorie...', NULL, 'application/jso...')
#1 /www/promocionesmovistar/htdocs/app/code/community/MercadoPago/Model/Source/CategoryId.php(25): MPRestClient::get('/item_categorie...')
#2 /www/promocionesmovistar/htdocs/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(463): MercadoPago_Model_Source_CategoryId->toOptionArray(false)
#3 /www/promocionesmovistar/htdocs/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#4 /www/promocionesmovistar/htdocs/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#5 /www/promocionesmovistar/htdocs/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#6 /www/promocionesmovistar/htdocs/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#7 /www/promocionesmovistar/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#8 /www/promocionesmovistar/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#9 /www/promocionesmovistar/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /www/promocionesmovistar/htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#11 /www/promocionesmovistar/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /www/promocionesmovistar/htdocs/index.php(87): Mage::run('', 'store')
#13 {main}";s:3:"url";s:89:"/index.php/admin/system_config/edit/section/payment/key/631ada31cf59a157edbd1f02d109cc0e/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by flaviadm** [comment]
Hola, encontraste la solución?

**Comment by fcapua-summa** [comment]
@flaviadm, ¿estás teniendo este problema? ¿probaste bajando la última versión del módulo?

**Comment by flaviadm** [comment]
Hola! Si, baje el ultimo y me aparece ese error en la configuración de métodos de pago...

**Comment by flaviadm** [comment]
Probe con el modulo anterior (mpexpress) y ese funciona. Tengo magento 1.9.0.0. El problema es que necesito integrar mercadoenvios y la versión anterior no dispone de ese modulo

**Comment by fcapua-summa** [comment]
Necesitaría alguno datos del servidor en donde estás obteniendo el error:
- Sistema Operativo (Nombre y versión)
- Versión de PHP
- Versión de la librería OpenSSL

Gracias!

**Comment by flaviadm** [comment]
Windows 10
PHP Version 5.6.15
OpenSSL/1.0.2d

**Comment by fcapua-summa** [comment]
@flaviadm eso no está dentro del listado de software requerido para correr Magento, como puedes revisar aqui: http://devdocs.magento.com/guides/m1x/system-requirements.html

Mi recomendación es que instales en un entorno compatible con Magento y si sigue fallando nos avises para que podamos ayudarte a solucionarlo.

Saludos!
