### ISSUE TITLE
Erro - CC Transparente

### ISSUE THREAD

**Issue by joa0vit0r** [mercadopago/cart-magento#89]
Olá,

Ao tentar realizar o pagamento via Cartão de Crédito Transparente, recebemos a seguinte mensagem:
Não foi possível processar o pagamento. {"status":400,"response":{"message":"invalid parameters","error":"bad_request","status":400,"cause":[{"code":"1067","description":"Invalid card token"}]}} 

Seriam dados inválidos?

**Comment by gerbesf** [comment]
Mesmo problema.

**Comment by paulo9** [comment]
tem que passar o seu form de dados para essa função, e com o token que ele retorna passar como parâmetro...  

Mercadopago.createToken($form, sdkResponseHandler)

encontrará mais informações aqui.. https://www.mercadopago.com.br/developers/pt/solutions/payments/custom-checkout/charge-with-creditcard/javascript/

**Comment by fcapua-summa** [comment]
Este problema não pode ser reproduzido com a nova versão do plug-in, que pode ser baixado a partir do seguinte link: https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x

Se o problema persistir por favor, crie uma outra questão.

Thanks!
