### ISSUE TITLE
New Order email

### ISSUE THREAD

**Issue by nacho22martin** [mercadopago/cart-magento#94]
Hola,

Cuando termino el checkout, se envia un mail al comprador de "cometario del pedido" o "order updated" no el de new order o nuevo pedido.

Es un motor de magento 1.9.1.1

Espero su respuesta. GRacias

**Comment by mroffe** [comment]
Nacho, pensá que Magento genera la orden y le cambia el estado según el resultado de Mercado Pago, es decir, saltea el envío de la orden y envía directamente la factura (si corresponde). El estado puede ser aceptado, rechazado, denegado, cancelado, etc.

**Comment by nacho22martin** [comment]
Gracias Martin,

Es correcto, pero en el email template de nueva orden incluye información
completa del pedido q seria bueno q el cliente la reciba... si no hay forma
de lograr q mande el mail de nueva orden y posterior el de cambio de estado
supongo q sera cuestión de incluir en los mails de cambio de estado toda la
info del pedido.

entendes mi punto?

gracias

**Comment by fcapua-summa** [comment]
Esto es parte de la nueva versión del plugin que se puede descargar desde aquí: https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x

Cualquier cosa pueden crear otro ticket, este lo doy por cerrado.

Muchas gracias!
