### ISSUE TITLE
Problema Incompatibilidade javascript Mozilla Firefox 40.0.3

### ISSUE THREAD

**Issue by thurow** [mercadopago/cart-magento#97]
Boa tarde,

Estou querendo implementar este módulo em um projeto, estava realizando algumas compras testes para ver se ocorria tudo normal. No Google Chrome funcionou perfeitamente. Já no Firefox não está selecionando a bandeira do cartão, e em consequência não posso selecionar a quantidade de vezes para pagar.

Ative os logs do mercadopago.js e nos dois navegadores, segue anexo:

![screenshot from 2015-11-26 15 19 34](https://cloud.githubusercontent.com/assets/14911960/11428469/f515cdd6-9452-11e5-87ab-c0b9e5e5614a.png)

![screenshot from 2015-11-26 15 23 45](https://cloud.githubusercontent.com/assets/14911960/11428472/fc776e54-9452-11e5-9774-e6e7a03559cf.png)

Projeto na versão 1.8.1.0 do magento, Módulo MercadoPago Transparente (Somente Cartões).
Att.

**Comment by fcapua-summa** [comment]
Este problema no se pudo reproducir con la nueva versión del plugin, la cual se puede descargar desde el siguiente link: https://github.com/mercadopago/cart-magento/tree/master/1.6.x-1.9.x

Si el problema persiste por favor crea otro issue.

Gracias!
