### ISSUE TITLE
Error en conversión de moneda a MP

### ISSUE THREAD

**Issue by mroffe** [mercadopago/cart-magento#99]
Ocurre que si tenemos un sitio que tiene como moneda base U$S y ademas, Euros y Pesos Argentinos, al enviar el total del pedido a Mercado Pago, lo convierte a U$S en lugar de a Pesos Argentinos.

Suponiendo que compramos por 100 Euros y el tipo de cambio da U$S 108, el modulo de Mercado Pago toma como que se deben pagar $ 108 (pesos argentinos).

**Comment by mroffe** [comment]
Algun comentario al respecto sobre este bug por favor.

**Comment by jorgevenzon** [comment]
Hola mroffe, tengo el mismo problema y modifiqué el archivo app/code/community/MercadoPago/Model/Standard/Payment.php, para que convierta el valor a pesos argentinos. En línea 41 protected $_BaseCurrency="ARS"; podés modificar la moneda de destino a la cual queres convertir.

Por las dudas te aclaro, esto no es oficial pero quizás te ayude mi solución. Hacé un backup del archivo y si podés probarlo en un entorno de desarrollo mejor. Lo probé en magento 1.9.2.2 y de momento parece funcionar muy bien.


[Payment.zip](https://github.com/mercadopago/cart-magento/files/95157/Payment.zip)

Saludos Jorge
kudosestudio.com

**Comment by mroffe** [comment]
Gracias Jorge por el dato. Yo esperaba que lo solucionen en el propio módulo ya que como está ahora, no sirve para tiendas internacionales.

**Comment by barbazul** [comment]
Esto es un bug, claramente.

En versiones anteriores del módulo estaba contemplado seleccionar la moneda con la que se pagaría en MP y te hacía la conversión correspondiente.

**Comment by fcapua-summa** [comment]
Estamos revisando este tema, vamos a actualizar el issue  en breve.

Gracias!

**Comment by mroffe** [comment]
Facundo, tenes alguna novedad de este bug?. 
Acabo de instalar la ultima versión y seguimos con lo mismo y solo no es todo, ahora tambien Mercado Envío cotiza con error. Un paquete de 30x30x30 a CABA lo cotiza $ 1620 ya que OCA devuelve 108 (sin especificar la moneda) y mi magento lo toma como USD 108 que a $ 15, da $ 1620

**Comment by ferxtr** [comment]
Hola, tengo el mismo problema que mroffe. alguien lo pudo solucionar ?

**Comment by gmatsuoka** [comment]
Actualmente el módulo no soporta la conversión de monedas.

**Comment by barbazul** [comment]
@mroffe Me da la impresión de que el problema lo tenés que corregir en el módulo de Oca

Nosotros tenemos un módulo de integración con Oca que contempla justamente este escenario y el mismo lo resuelve convirtiendo la tarificación obtenida del servicio de Oca a la moneda base de la tienda para homogenizar con el resto de los cálculos (por ejemplo MP).

Un problema similar puede que lo estés experimentando con los impuestos. El servicio SOAP de Oca responde todas las tarifas excluyendo IVA y dependiendo de cómo tengas configurada la tienda puede que estés asumiendo precios finales en el resto de los cálculos.
